### ISSUE TITLE
Web Interface clips bottom of displayed content 

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#102]
As the display scrolls with syslog or the snipswatch the last entry does not show except very tips of the characters. The bottom of that page is unreachable (for me at least) and does not scale to browser size.  My laptop screen is max at 1366x768 (16x9) 
A sightly shorter text box would resolve the issue, also maybe for others? 
Thanks

**Comment by Psychokiller1888** [comment]
I can't repro this

![https://puu.sh/Ev1fq.png](https://puu.sh/Ev1fq.png)

This is on 3840x1080. The only way I can repro is by zooming the page at above 200% which is due to fail

**Comment by Psychokiller1888** [comment]
1920x1080 work screen

![https://puu.sh/Ev56F.png](https://puu.sh/Ev56F.png)

**Comment by mjlill** [comment]
Thanks for looking at it. If someone wants to use the "official" 7" Pi screen as a display I believe the issue would show even worse? It is fine on a larger screen, but can't resize the text box so loose the bottom line. Not a show stopper for sure but is an issue  :)

**Comment by mjlill** [comment]
Computer display issue do to screen size
