### ISSUE TITLE
retrain voice hotword

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#108]
Hi there, how can i reset the "hey alice" hotword if i've done the training but she doesn't respond to it please ?

**Comment by LazzaWA** [comment]
all sorted,
 i manually trimmed the 3 wav files in /ProjectAlice/trained/hotwords/<my-name>.
Probably still nice to know if there's something we can change to reset the hotword process ? :)

**Comment by Psychokiller1888** [comment]
It's not yet implemented, as I had to implement the pin auth first to get to that. But it's planned

**Comment by SkyHyperV** [comment]
You can restart the process by removing the entry from ~/ProjectAlice/database/data.db file or if only 1 user is defined, you can delete the file and restart ProjectAlice service.

**Comment by maxbachmann** [comment]
@Psychokiller1888 now that we have the Pin Auth we could add this
