### ISSUE TITLE
OS independence

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/ProjectAlice#11]
Though Snips is not yet available on every OS, our code should be os indenpendent.

Meaning path using a concatenation style: '{}/{}/{}'.format(foo, bar, baz) is a big no. Instead use os.path.join(foo, bar, baz) or better yet, Python 3 Path objects

Other exemples are os.path.join('/tmp', 'myfile.ext'), that's a no too! Instead use os.path.join(tempfile.gettempdir(), 'myfile.ext)

Other exemples if needed, but I think we got the idea

**Comment by maxbachmann** [comment]
is there any reason to keep a won't fix open?
