### ISSUE TITLE
Skill vs Module

### ISSUE THREAD

**Issue by maxbachmann** [project-alice-assistant/ProjectAlice#134]
All other voice assistants I know have skills, while we have modules. We should probaby simply rename it to skills aswell to make it more clear to users what they are.

**Comment by Psychokiller1888** [comment]
Renaming goes a bit further though, as everything that contains "module" should also be renamed: ModuleManager, moduleInstance = foo etc etc. Regex power!

**Comment by maxbachmann** [comment]
yeah definetly has to be done everywhere. Otherwise this will be super confusing
