### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by maxbachmann** [project-alice-assistant/ProjectAlice#138]
we need a better documentation for the whole project. The most important topics right now are:
- how to set Alice up
- how to create Skills for Alice
However documentation on other topics is definetly welcome. The documentation is based on vuepress, which generates a wiki based on Markdown files (the theme can be created in Vue.js, but the default theme is already pretty good). The current state of the docs can be found in https://github.com/project-alice-assistant/docs and are served https://project-alice-assistant.github.io/docs/ here.

I do not really have enough time with all the other things that need to be done on Alice, so I would be super happy when other people would write some documentation aswell :pray:

**Comment by Alex-Lewa-95-RPI-Noob** [comment]
I created the german documentation.
https://bbarblexi.gitbook.io/projectalice-de/

**Comment by Psychokiller1888** [comment]
@Alex-Lewa-95-RPI-Noob ! That's great, thank you very much! We now need to move it to our open source doc on docs.projectalice.io. Will add i18n support today so it can be transported to our own servers

**Comment by Psychokiller1888** [comment]
@Alex-Lewa-95-RPI-Noob Added german support https://docs.projectalice.io/de/

**Comment by philipp2310** [comment]
whew... started translating yesterday as well - just happy I found this now before I'm done ;D
Will move it over to the official page tomorrow! Thank you :)
