### ISSUE TITLE
Skill Website

### ISSUE THREAD

**Issue by maxbachmann** [project-alice-assistant/ProjectAlice#142]
We do extract all skills to a store.json, that can be found at:
alice.maxbachmann.de/assets/<branchName>/store/store.json.
It would be cool to have a website showing all modules at alice.maxbachmann. The informations could be taken from the extracted store.json and the readme files of each skill.

**Comment by Psychokiller1888** [comment]
Although it seems like a very good idea, I kindda got used to the idea that everything runs on device, even the skill store, that way we are transparent when it comes to third party website tracking and all. What do you think? Build something better on the interface?

**Comment by maxbachmann** [comment]
I think it would be useful to have a website that shows them for people that do not have a installed version. Could be somewhat integrated with the documentations, so people that are new to the project can see which skills exist.
This could be somewhat integrated with our documentation. On the tracking I would just have the website code open source and auto deploy it with a ci. Guess thats pretty transparent on what we are doing on there (and on the tracking part I would just not add third party tracking stuff)

**Comment by Psychokiller1888** [comment]
The people not having it installed is a good argument, you are correct

**Comment by maxbachmann** [comment]
yeah even though https://github.com/project-alice-assistant/ProjectAlice/issues/138 is apparently more important right now

**Comment by philipp2310** [comment]
Documentation/directions for skills is something that is being asked for from time to time as well.
My Suggestion: the "on device" skill store has per skill (installed or not) an automatically generated link to the documentation (e.g. docs.projectalice.io/skill/AliceSatellite ) of course these links are available from the documentation itself as well.

On these documentations I would expect Information like:
- Broader description general functionality (showcase before you install the skill or even Alice!)
- installation hints (what API keys do you need, what information do you have to provide, what external hardware is supported etc.)
- description of the possible commands (the on device overview of commands is a good start, but sometimes a bit more of a tutorial might be good)

**Comment by maxbachmann** [comment]
> Edit: After re-reading everything here - maybe a CI could copy the README to the right folder in the documentation?
My idea back then was to use informations both from the `*.install` (e.g. for icon and version) and the README to auto generate them
-> basically general information from the install file and then simply the whole readme as a description on how to use it
