### ISSUE TITLE
Intents not shown in skills view

### ISSUE THREAD

**Issue by twigz20** [project-alice-assistant/ProjectAlice#148]
In the Skills View, after clicking on the "View Intents" button, the intents are missing.
See image below.
![Screenshot_10](https://user-images.githubusercontent.com/10361408/70963912-ec7bc780-2057-11ea-8e79-f980fb3e7931.png)

**Comment by Psychokiller1888** [comment]
![https://puu.sh/EQtCB.png](https://puu.sh/EQtCB.png)
