### ISSUE TITLE
develop snips watch alternative

### ISSUE THREAD

**Issue by maxbachmann** [project-alice-assistant/ProjectAlice#150]
snips watch in the web interface has about 1 sec delay to the actual snips watch when run on the device. This makes alice feel a lot less responsive.
I guess this is set by
```js
	setInterval(function () {
		refreshData();
	}, 500);
```
and half a second more delay is quite a bit

**Comment by Psychokiller1888** [comment]
I guess we should subscribe, could maybe use mqtt for this maybe

**Comment by maxbachmann** [comment]
yeah I am not quite sure whether we can still use it with the next release anyways.
And it is not open source + bad maintained (the command flags do not even what they are supposed to do ...)
