### ISSUE TITLE
New install without snips console

### ISSUE THREAD

**Issue by tsvsj** [project-alice-assistant/ProjectAlice#166]
Hi,

I'd like to give this project a try. Unfortunately I cannot start the daemon, as I don't have a snips console account and can't create an account, because new registrations are blocked, since the console is being closed by the end of January 2020. Is there a backup plan? I thought that Project Alice is working with Google or AWS instead of snips. Did I miss something?

Thanks for helping me.

Cheers,
tsvsj

**Comment by Psychokiller1888** [comment]
Hi!

As of now you can't you need a snips account because we are still linked to snips. We are working to brake that bond though

**Comment by tsvsj** [comment]
Hi,

sounds great. Thanks for your response. Don't want to push you, but do you have an idea how long it will take to leave snips?

**Comment by maxbachmann** [comment]
since snips is only available until the end of january we will replace it untile then aswell

**Comment by tsvsj** [comment]
Perfect! Thanks for this information and for your work!

**Comment by tsvsj** [comment]
Any update on this? I was reviewing the milestones and open issues, but wasn't able to find any issue related to the replacement of snips.

**Comment by Psychokiller1888** [comment]
This is now completed
