### ISSUE TITLE
MQTT Protocol

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/ProjectAlice#172]
We need to clearly define the structure of our internal mqtt communication. Some components follow the Hermes protocol:

`hermes/intents/foo`
`hermes/nlu/bar`

1. Are we implementing hermes? Such as `hermes/events/onDoorClosed`
2. Are we rather use our own convention? Such as `alice/events/onDoorClosed`

How do we structure? We actually have a few things to communicate through mqtt:
- Devices
- Zigbee2Mqtt
- Node Red
- All the voice components

The idea could be
- hermes/device/telemetryReport
- hermes/zigbee/telemetryReport
- hermes/events/onTemperatureTooHigh
- hermes/COMPONENT/action such as `hermes/hotword/detected`

**Comment by maxbachmann** [comment]
I like the basic stuff hermes does, but I think we should specify a own structure for all our stuff that uses ideas from hermes. Using hermes or mixing it with own specs without renaming it will confuse people.

maybe use some other name of a messenger of the gods like e.g. Garuda ;)

**Comment by maxbachmann** [comment]
Is zigbee stuff send over mqtt?

**Comment by Psychokiller1888** [comment]
In that case it would become

- projectalice/device/telemetryReport
- projectalice/zigbee/telemetryReport
- projectalice/events/scenariosConnected
- projectalice/COMPONENT/action

**Comment by maxbachmann** [comment]
yes
