### ISSUE TITLE
Hotword service

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/ProjectAlice#196]
Prepare to move to hotword service independant Alice.

Things to remember is that we need to auth the user through that hotword.

**Comment by philipp2310** [comment]
Status update, currently supported wakeword engines:
- snips (user specific ww creation guided by Alice, with user recognition)
- porcupine
- precise

Therefore Alice is snips independent, but still a wakeword engine with user recognition is needed.
- snowboy (shutting down)
