### ISSUE TITLE
fixed user name 'pi'  in ProjectAlice/core/voice/model/TTS.py  should be replaced

### ISSUE THREAD

**Issue by reklawykSekuL** [project-alice-assistant/ProjectAlice#199]
Line 80:  
			subprocess.run(['sudo', 'chown', 'pi', str(self.TEMP_ROOT)])
should be changed to:
			subprocess.run(['sudo', 'chown', getpass.getuser(), str(self.TEMP_ROOT)])

**Comment by Psychokiller1888** [comment]
Thank you!
