### ISSUE TITLE
skill: random speaking continues after UI check disables

### ISSUE THREAD

**Issue by hipitihop** [project-alice-assistant/ProjectAlice#203]
Red Queen skill: random speaking continues after disabled in GUI via check box.

version: 1.0.0-a5

![image](https://user-images.githubusercontent.com/4626024/75131151-634ed400-571d-11ea-9d56-e66922b0cb3a.png)

**Comment by Psychokiller1888** [comment]
Fixed in 1.0.19. Will update automatically if skill auto update = true, or on next Alice boot
