### ISSUE TITLE
TTS defaults not correct ProjectAlice.yaml 

### ISSUE THREAD

**Issue by hipitihop** [project-alice-assistant/ProjectAlice#205]
The default in ProjectAlice.yaml use `Female` and `Joanna`, these should probably be `male` and `en-US`

https://github.com/project-alice-assistant/ProjectAlice/blob/9101ce57d03a1e9b939cdc4019e6c20fd811e736/ProjectAlice.yaml#L119-L120

**Comment by Psychokiller1888** [comment]
Corrected
