### ISSUE TITLE
DeepSpeech error when switching from google

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#214]
After Alice downloaded and installed DeepSpeech, switching from google ASR to DeepSpeech comes up with the following error and therefore fails to start. This is on fresh install and git pull to a6. Switching back to google ASR is ok

> ProjectAlice python3[15359]: ERROR: Mmap of '/home/pi/ProjectAlice/trained/asr/deepspeech/en/deepspeech-0.6.1-models/output_graph.tflite' failed.
Mar  8 09:35:00 ProjectAlice python3[15359]: Error at reading model file /home/pi/ProjectAlice/trained/asr/deepspeech/en/deepspeech-0.6.1-models/output_graph.tflite
Mar  8 09:35:00 ProjectAlice python3[15359]: An unhandled exception occured
Mar  8 09:35:00 ProjectAlice python3[15359]: - Traceback: Traceback (most recent call last):
Mar  8 09:35:00 ProjectAlice python3[15359]:   File "main.py", line 114, in <module>
Mar  8 09:35:00 ProjectAlice python3[15359]:     main()
Mar  8 09:35:00 ProjectAlice python3[15359]:   File "main.py", line 88, in main
Mar  8 09:35:00 ProjectAlice python3[15359]:     projectAlice = ProjectAlice(restartHandler=restart)
Mar  8 09:35:00 ProjectAlice python3[15359]:   File "/home/pi/ProjectAlice/core/ProjectAlice.py", line 28, in __init__
Mar  8 09:35:00 ProjectAlice python3[15359]:     self._superManager.onStart()
Mar  8 09:35:00 ProjectAlice python3[15359]:   File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 88, in onStart
Mar  8 09:35:00 ProjectAlice python3[15359]:     manager.onStart()
Mar  8 09:35:00 ProjectAlice python3[15359]:   File "/home/pi/ProjectAlice/core/asr/ASRManager.py", line 27, in onStart
Mar  8 09:35:00 ProjectAlice python3[15359]:     self._startASREngine()
Mar  8 09:35:00 ProjectAlice python3[15359]:   File "/home/pi/ProjectAlice/core/asr/ASRManager.py", line 75, in _startASREngine
Mar  8 09:35:00 ProjectAlice python3[15359]:     self._asr.onStart()
Mar  8 09:35:01 ProjectAlice python3[15359]:   File "/home/pi/ProjectAlice/core/asr/model/DeepSpeechASR.py", line 47, in onStart
Mar  8 09:35:01 ProjectAlice python3[15359]:     self._model = deepspeech.Model(f'{self._langPath}/deepspeech-0.6.1-models/output_graph.tflite', 500)
Mar  8 09:35:01 ProjectAlice python3[15359]:   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/deepspeech/__init__.py", line 42, in __init__
Mar  8 09:35:01 ProjectAlice python3[15359]:     raise RuntimeError("CreateModel failed with error code {}".format(status))
Mar  8 09:35:01 ProjectAlice python3[15359]: RuntimeError: CreateModel failed with error code 12288
Mar  8 09:35:01 ProjectAlice systemd[1]: ProjectAlice.service: Main process exited, code=exited, status=1/FAILURE
Mar  8 09:35:01 ProjectAlice systemd[1]: ProjectAlice.service: Failed with result 'exit-code'.
Mar  8 09:35:06 ProjectAlice systemd[1]: ProjectAlice.service: Service RestartSec=5s expired, scheduling restart.
Mar  8 09:35:06 ProjectAlice systemd[1]: ProjectAlice.service: Scheduled restart job, restart counter is at 11.
Mar  8 09:35:06 ProjectAlice systemd[1]: Stopped Project Alice.

**Comment by Psychokiller1888** [comment]
Can you check if you have the deepspeech model in ProjectAlice/trained/asr/deepspeech/en?

**Comment by LazzaWA** [comment]
i believe i do yes.

> pi@ProjectAlice:~/ProjectAlice/trained/asr/deepspeech/en/deepspeech-0.6.1-models $ ls -l
total 11016
-rw-r--r-- 1 pi pi 11276288 Dec  3 07:51 lm.binary
-rw-r--r-- 1 pi pi        0 Dec  3 10:03 output_graph.pb
-rw-r--r-- 1 pi pi        0 Dec  3 10:49 output_graph.pbmm
-rw-r--r-- 1 pi pi        0 Jan 10 18:21 output_graph.tflite
-rw-r--r-- 1 pi pi        0 Dec  3 07:51 trie

**Comment by LazzaWA** [comment]
the only references i can find on google for  `RuntimeError: CreateModel failed with error code 12288` points towards deepspeech and tensorflow version missmatch, however suspect that's not the case here seeing as it works on other peoples installs.

**Comment by LazzaAU** [comment]
Update to the issue.

Although i've never seen any reference to memory issues in my syslogs.. `dmesg` mentions swap file running out of space. So i adjusted the swap file size to 1024. Also while on this line of thought i checked partition size and due to running my PI on a USB stick i used gparted to allocate the unallocated partition to PA and i was then able to install DS

So the tip for those that may get this error especially if on USB... check your not running out of memory and/or storage space .
