### ISSUE TITLE
onHotwordToggleOn does not work

### ISSUE THREAD

**Issue by poulsp** [project-alice-assistant/ProjectAlice#220]
In a user skill 'def onHotwordToggleOn(self, siteId: str):'  does not work
In core/server/MqttManager.py
line: 181: elif message.topic == constants.TOPIC_HOTWORD_TOGGLE_ON:
Line 182
  self.broadcast(method=constants.EVENT_HOTWORD_TOGGLE_ON, exceptions=[constants.DUMMY], siteId=siteId)
should be changed to:
self.broadcast(method=constants.EVENT_HOTWORD_TOGGLE_ON, exceptions=[constants.DUMMY], propagateToSkills=True, siteId=siteId)
for it to work.

Why is there not an EVENT HOTWORD_TOGGLE_OFF.
Right now you have to use @MqttHandler('hermes/hotword/toggleOff').
Not consistent.

**Comment by Psychokiller1888** [comment]
Thanks! Just fixed it
