### ISSUE TITLE
[BUG] Deepspeech re downloading

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#233]
On the a6 version and also now the b1 version i have been facing a issue with the "en" folder that DeepSpeech (DS) gets downloaded into being deleted during a restart and/or changing from DS to google ASR.

**The short story is :** when switching to DS it then downloads and installs the required files into /ProjectAlice/trained/asr/deepspeech/en as shown below,

> pi@ProjectAlice:~/ProjectAlice/trained/asr/deepspeech/en/deepspeech-0.6.1-models $ ls -l
total 1350668
-rw-r--r-- 1 pi pi 945699324 Dec  3 16:51 lm.binary
-rw-r--r-- 1 pi pi 188914896 Dec  3 19:03 output_graph.pb
-rw-r--r-- 1 pi pi 188915850 Dec  3 19:49 output_graph.pbmm
-rw-r--r-- 1 pi pi  47331120 Jan 11 03:21 output_graph.tflite
-rw-r--r-- 1 pi pi  12200736 Dec  3 16:51 trie

Not sure the complete trigger but restarting Alice or swapping between DS and google causes the  /ProjectAlice/trained/asr/deepspeech/en folder to be deleted and therefore DS to start re downlading

**The extended logs ( with my comments inside the log for debugging )** 

Please see attached log file
[DSdownloadLog.log](https://github.com/project-alice-assistant/ProjectAlice/files/4372850/DSdownloadLog.log)

**Comment by Psychokiller1888** [comment]
Something is off here, the snips services shouldn't try to restart all the time, they should be disabled by the initialyser... hmmm

**Comment by Psychokiller1888** [comment]
Office is something I have fixed on master. Make sure constants.py is set to default and that the audio server "bind" is commented out in snips.toml

**Comment by Psychokiller1888** [comment]
Should be ok now

**Comment by LazzaAU** [comment]
Agreed.. three attempts to break it and i can't :) good work captain

**Comment by LazzaAU** [comment]
Need to reopen this as it persists but the cause has probably been narrowed down.

 Clicking the "update" button in the UI instantly deletes the en folder and therefore DS re downloads. Suspect when it auto updates this also might happen as i lost the folder this morning and hadnt clicked update. However a definite trigger is clicking "update"
