### ISSUE TITLE
[Bug] in CommonsManager, return wrong session.slots. Replaces issue #228

### ISSUE THREAD

**Issue by poulsp** [project-alice-assistant/ProjectAlice#234]
Replaces issue #228
The return value is the slots rawValue and not the real slots.
So synonyms dont work, because it's the synonyms there is returned.

line 100 in CommonsManager.py
```@classmethod
def parseSlots(cls, message: MQTTMessage) -> dict:
    data = cls.payload(message)
    return {slot['slotName']: slot['rawValue'] for slot in data.get('slots', dict())}```
should be
```return {slot['slotName']: slot['value']['value'] for slot in data.get('slots', dict())}```

**Comment by Psychokiller1888** [comment]
That's normal, you have both session.slotValue and session.slotRawValue

**Comment by poulsp** [comment]
session.slots['Room'] return the synonym not the real actual slot.
in my skill session.slots returns {'Room': 'gaming room'}
session.slots['Room'] returns 'gaming room'

**Comment by Psychokiller1888** [comment]
Need to define what's real and what's not. Is the real value what was heard or the master value? That's a point of view imo

**Comment by poulsp** [comment]
in the defs of a slottype pouls/room
```"slotTypes": [
  {
    "name": "Poulsp/Room",
    "matchingStrictness": null,
    "automaticallyExtensible": true,
    "useSynonyms": true,
    "values": [

      {
        "value": "office",
        "synonyms": [
          "gaming room"
        ]
      },

**Comment by Psychokiller1888** [comment]
session.slotValue('Room') = 'office'
session.slotRawValue('Room') = 'gaming room'
