### ISSUE TITLE
[bug] in TomlFile.py

### ISSUE THREAD

**Issue by poulsp** [project-alice-assistant/ProjectAlice#239]
Bug in class TomlFile _load(self):
If you want to have constant.DEFAULT_SITE_ID = 'office' instead of 'default' you can set it in snips.toml as below,
but  TomlFile _load() choose 'default' instead of 'office'.
If you put two or more hash marks (##bind = "default@mqtt") it wil work
```[snips-audio-server]
bind = "office@mqtt"
#bind = "default@mqtt"

**Comment by Psychokiller1888** [comment]
Yes, it's because `bind`and `#bind` is the same, one is active, the other not and `##bind` is a comment. That's not a bug, it's a design decision of mine
