### ISSUE TITLE
[GUI] Options titlebar default off

### ISSUE THREAD

**Issue by philipp2310** [project-alice-assistant/ProjectAlice#241]
when you enter the options menu, the titlebar is displayed as off, even if it is currently shown. If you don't turn it on, it will be saved as off and disappear.

I can fix it - just a reminder for later ;)

**Comment by philipp2310** [comment]
(aand move the NLU training back to the left side ^^)

**Comment by Psychokiller1888** [comment]
My bad, had a brain fart...
