### ISSUE TITLE
[GUI] Z-Sorting on skill level

### ISSUE THREAD

**Issue by philipp2310** [project-alice-assistant/ProjectAlice#243]
If you have two widgets in one skill, they have a fixed Z-sort order. If you change a third widgets Z-order, the two widgets of one skill, will be reset to their initial order.

Changing one widget of the two, will move BOTH in front of the third widget.

Idea: rework Z-Ordering, offer a drag and drop list: sort by drag and drop. Can be combined with the new "add Widget" dialog, that supports multiple instances of one widget.

**Comment by Psychokiller1888** [comment]
Implemented
