### ISSUE TITLE
[GUI] Reload widgets as soon as ready

### ISSUE THREAD

**Issue by philipp2310** [project-alice-assistant/ProjectAlice#245]
When the interface is opened too early (autostart on raspi, already open on remote PC) the widgets are not yet loaded
Completely missing widgets -> maybe hook into mqtt, reload the complete side when Alice is fully started (Only if Alice was not running on page load, or is currently in no menu (toolbar closed))
Widgets loaded, data function not yet ready -> automatically retry loading the widget until data is available

**Comment by Psychokiller1888** [comment]
Tried something yesterday, didn't work, will try another way today

**Comment by philipp2310** [comment]
by reloading the page without a heartbeat, a reload after alice has started is almost guaranteed. shouldn't be a problem anymore!
