### ISSUE TITLE
Beginner: first installation does not work (no random speaking)

### ISSUE THREAD

**Issue by milode** [project-alice-assistant/ProjectAlice#247]
Sorry I am complete beginner an not a programmer, but maybe you want to help:
I have a new installation
**HW:** Raspberry pi 4 with 2 GB ram, USB-speaker, Mic: MatrixVoice

**Problem:** ProjectAlice not working (no random speaking, no LED activity)
See below output from
-  **"sudo systemctl status ProjectAlice":**
and
- **~/ProjectAlice $ ./venv/bin/python main.py**

Thank you for support!
best regards 
Michael

**output from "sudo systemctl status ProjectAlice":**
pi@ProjectAlice:~/ProjectAlice $ sudo systemctl status ProjectAlice
● ProjectAlice.service - Project Alice
   Loaded: loaded (/etc/systemd/system/ProjectAlice.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-04-19 11:10:03 CEST; 13s ago
  Process: 6278 ExecStartPre=/bin/sleep 5 (code=exited, status=0/SUCCESS)
 Main PID: 6279 (python3)
    Tasks: 9 (limit: 4035)
   Memory: 166.6M
   CGroup: /system.slice/ProjectAlice.service
           └─6279 /home/pi/ProjectAlice/venv/bin/python3 main.py

Apr 19 11:10:14 ProjectAlice python3[6279]: [Manager] Starting NodeRedManager
Apr 19 11:10:14 ProjectAlice python3[6279]: [NodeRedManager] New scenario node found
Apr 19 11:10:14 ProjectAlice sudo[6376]:       pi : TTY=unknown ; PWD=/home/pi/ProjectAlice ; USER=root ; COMMAND=/bin/systemctl start nodered
Apr 19 11:10:14 ProjectAlice sudo[6376]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 19 11:10:14 ProjectAlice sudo[6376]: pam_unix(sudo:session): session closed for user root
Apr 19 11:10:14 ProjectAlice sudo[6385]:       pi : TTY=unknown ; PWD=/home/pi/ProjectAlice ; USER=root ; COMMAND=/bin/systemctl start hermesledcontrol
Apr 19 11:10:14 ProjectAlice sudo[6385]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 19 11:10:14 ProjectAlice sudo[6385]: pam_unix(sudo:session): session closed for user root
Apr 19 11:10:14 ProjectAlice python3[6279]: [RedQueen] Scheduled next random speaking in 933 seconds
Apr 19 11:10:14 ProjectAlice python3[6279]: [main] - Started Project Alice in 10.59 seconds

**Output from: pi@ProjectAlice:~/ProjectAlice $ ./venv/bin/python main.py**

[Initializer] Starting Project Alice initializer
[Initializer] No initialization needed
[main] Starting up Project Alice
[Manager] Initializing Commons
[Manager] Initializing ConfigManager
[ConfigManager] Checking Alice configuration file
[ConfigManager] Loading Snips configuration file
[ConfigManager] Checking configuration for skill DateDayTimeYear
[ConfigManager] Checking configuration for skill ContextSensitive
[ConfigManager] Checking configuration for skill Telemetry
[ConfigManager] Checking configuration for skill AliceCore
[ConfigManager] Checking configuration for skill RedQueen
[Manager] Initializing DatabaseManager
[Manager] Initializing LanguageManager
[Manager] Initializing SnipsServicesManager
[Manager] Initializing ASRManager
[Manager] Initializing TTSManager
[Manager] Initializing ThreadManager
[Manager] Initializing ProtectedIntentManager
[Manager] Initializing MqttManager
[Manager] Initializing TimeManager
[Manager] Initializing UserManager
[Manager] Initializing DialogSessionManager
[Manager] Initializing MultiIntentManager
[Manager] Initializing TelemetryManager
[Manager] Initializing SkillManager
[Manager] Initializing DeviceManager
[Manager] Initializing InternetManager
[Manager] Initializing WakewordManager
[Manager] Initializing TalkManager
[Manager] Initializing WebInterfaceManager
[Manager] Initializing NodeRedManager
[Manager] Initializing SkillStoreManager
[Manager] Initializing DialogTemplateManager
[Manager] Initializing SnipsAssistantManager
[Manager] Initializing NluManager
[NluEngine] Starting Snips NLU
[SnipsServicesManager] Service snips-nlu start'ed
[Manager] Initializing AliceWatchManager
[Manager] Starting Commons
[Manager] Starting ConfigManager
[Manager] Starting LanguageManager
[LanguageManager] Active language set to "de-DE"
[LanguageManager] Default language set to "en-US"
[Manager] Starting InternetManager
[Manager] Starting SnipsServicesManager
[SnipsServicesManager] Service snips-hotword start'ed
[SnipsServicesManager] Service snips-dialogue start'ed
[SnipsServicesManager] Service snips-audio-server start'ed
[Manager] Starting DatabaseManager
[Manager] Starting UserManager
[UserManager] - Loaded 1 users
[Manager] Starting MqttManager
[Manager] Starting ASRManager
[ASR] Checking dependencies
[ASR] Starting Pocketsphinx ASR
INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/feat.params
Current configuration:
[NAME]                  [DEFLT]         [VALUE]
-agc                    none            none
-agcthresh              2.0             2.000000e+00
-allphone
-allphone_ci            yes             yes
-alpha                  0.97            9.700000e-01
-ascale                 20.0            2.000000e+01
-aw                     1               1
-backtrace              no              no
-beam                   1e-48           1.000000e-48
-bestpath               yes             yes
-bestpathlw             9.5             9.500000e+00
-ceplen                 13              13
-cmn                    live            current
-cmninit                40,3,-1         40,3,-1
-compallsen             no              no
-dict                                   /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/cmudict-de-de.dict
-dictcase               no              no
-dither                 no              no
-doublebw               no              no
-ds                     1               1
-fdict
-feat                   1s_c_d_dd       1s_c_d_dd
-featparams
-fillprob               1e-8            1.000000e-08
-frate                  100             100
-fsg
-fsgusealtpron          yes             yes
-fsgusefiller           yes             yes
-fwdflat                yes             yes
-fwdflatbeam            1e-64           1.000000e-64
-fwdflatefwid           4               4
-fwdflatlw              8.5             8.500000e+00
-fwdflatsfwin           25              25
-fwdflatwbeam           7e-29           7.000000e-29
-fwdtree                yes             yes
-hmm                                    /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de
-input_endian           little          little
-jsgf
-keyphrase
-kws
-kws_delay              10              10
-kws_plp                1e-1            1.000000e-01
-kws_threshold          1e-30           1.000000e-30
-latsize                5000            5000
-lda
-ldadim                 0               0
-lifter                 0               22
-lm                                     /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de.lm.bin
-lmctl
-lmname
-logbase                1.0001          1.000100e+00
-logfn
-logspec                no              no
-lowerf                 133.33334       1.300000e+02
-lpbeam                 1e-40           1.000000e-40
-lponlybeam             7e-29           7.000000e-29
-lw                     6.5             6.500000e+00
-maxhmmpf               30000           30000
-maxwpf                 -1              -1
-mdef
-mean
-mfclogdir
-min_endfr              0               0
-mixw
-mixwfloor              0.0000001       1.000000e-07
-mllr
-mmap                   yes             yes
-ncep                   13              13
-nfft                   512             512
-nfilt                  40              25
-nwpen                  1.0             1.000000e+00
-pbeam                  1e-48           1.000000e-48
-pip                    1.0             1.000000e+00
-pl_beam                1e-10           1.000000e-10
-pl_pbeam               1e-10           1.000000e-10
-pl_pip                 1.0             1.000000e+00
-pl_weight              3.0             3.000000e+00
-pl_window              5               5
-rawlogdir
-remove_dc              no              no
-remove_noise           yes             yes
-remove_silence         yes             yes
-round_filters          yes             yes
-samprate               16000           1.600000e+04
-seed                   -1              -1
-sendump
-senlogdir
-senmgau
-silprob                0.005           5.000000e-03
-smoothspec             no              no
-svspec
-tmat
-tmatfloor              0.0001          1.000000e-04
-topn                   4               4
-topn_beam              0               0
-toprule
-transform              legacy          dct
-unit_area              yes             yes
-upperf                 6855.4976       6.800000e+03
-uw                     1.0             1.000000e+00
-vad_postspeech         50              50
-vad_prespeech          20              20
-vad_startspeech        10              10
-vad_threshold          3.0             3.000000e+00
-var
-varfloor               0.0001          1.000000e-04
-varnorm                no              no
-verbose                no              no
-warp_params
-warp_type              inverse_linear  inverse_linear
-wbeam                  7e-29           7.000000e-29
-wip                    0.65            6.500000e-01
-wlen                   0.025625        2.562500e-02

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='batch', VARNORM='no', AGC='none'
INFO: acmod.c(152): Reading linear feature transformation from /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/feature_transform
INFO: mdef.c(518): Reading model definition: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/mdef
INFO: bin_mdef.c(181): Allocating 106225 * 8 bytes (829 KiB) for CD tree
INFO: tmat.c(149): Reading HMM transition probability matrices: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/transition_matrices
INFO: acmod.c(113): Attempting to use PTM computation module
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/means
INFO: ms_gauden.c(242): 6201 codebook, 1 feature, size:
INFO: ms_gauden.c(244):  16x29
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/variances
INFO: ms_gauden.c(242): 6201 codebook, 1 feature, size:
INFO: ms_gauden.c(244):  16x29
INFO: ms_gauden.c(304): 1077 variance values floored
INFO: ptm_mgau.c(803): Number of codebooks exceeds 256: 6201
INFO: acmod.c(115): Attempting to use semi-continuous computation module
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/means
INFO: ms_gauden.c(242): 6201 codebook, 1 feature, size:
INFO: ms_gauden.c(244):  16x29
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/variances
INFO: ms_gauden.c(242): 6201 codebook, 1 feature, size:
INFO: ms_gauden.c(244):  16x29
INFO: ms_gauden.c(304): 1077 variance values floored
INFO: acmod.c(117): Falling back to general multi-stream GMM computation
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/means
INFO: ms_gauden.c(242): 6201 codebook, 1 feature, size:
INFO: ms_gauden.c(244):  16x29
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/variances
INFO: ms_gauden.c(242): 6201 codebook, 1 feature, size:
INFO: ms_gauden.c(244):  16x29
INFO: ms_gauden.c(304): 1077 variance values floored
INFO: ms_senone.c(149): Reading senone mixture weights: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/mixture_weights
INFO: ms_senone.c(200): Truncating senone logs3(pdf) values by 10 bits
INFO: ms_senone.c(207): Not transposing mixture weights in memory
INFO: ms_senone.c(268): Read mixture weights for 6201 senones: 1 features x 16 codewords
INFO: ms_senone.c(320): Mapping senones to individual codebooks
INFO: ms_mgau.c(144): The value of topn: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 35749 * 20 bytes (698 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/cmudict-de-de.dict
INFO: dict.c(213): Dictionary size 31650, allocated 303 KiB for strings, 529 KiB for phones
INFO: dict.c(336): 31650 words read
INFO: dict.c(358): Reading filler dictionary: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/pocketsphinx/model/de-de/noisedict
INFO: dict.c(213): Dictionary size 31653, allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 3 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 67^3 * 2 bytes (587 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 54136 bytes (52 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 54136 bytes (52 KiB) for single-phone word triphones
INFO: ngram_model_trie.c(354): Trying to read LM in trie binary format
WARN: "hash_table.c", line 150: Very large hash table requested (1093543 entries)
WARN: "hash_table.c", line 150: Very large hash table requested (1093543 entries)
WARN: "hash_table.c", line 150: Very large hash table requested (1093545 entries)
INFO: ngram_search_fwdtree.c(74): Initializing search tree
INFO: ngram_search_fwdtree.c(101): 702 unique initial diphones
INFO: ngram_search_fwdtree.c(186): Creating search channels
INFO: ngram_search_fwdtree.c(323): Max nonroot chan increased to 104420
INFO: ngram_search_fwdtree.c(333): Created 701 root, 104292 non-root channels, 4 single-phone words
INFO: ngram_search_fwdflat.c(157): fwdflat: min_ef_width = 4, max_sf_win = 25
[Manager] Starting TTSManager
[TTSManager] Started "pico" TTS
[TTS] Language from config: "de-DE"
[TTS] Type from config: "female"
[TTS] Voice from config: "de-DE"
[TTS] Type "female" not found for the language, falling back to "male"
[Manager] Starting ProtectedIntentManager
[Manager] Starting ThreadManager
[Manager] Starting TimeManager
[Manager] Starting DialogSessionManager
[Manager] Starting MultiIntentManager
[Manager] Starting TelemetryManager
[Manager] Starting DeviceManager
[DeviceManager] - Loaded 0 devices
[Manager] Starting WakewordManager
[Manager] Starting WebInterfaceManager
[WebInterfaceManager] Loaded interface in "de"
 * Serving Flask app "core.interface.WebInterfaceManager" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
[Manager] Starting AliceWatchManager
[Manager] Starting TalkManager
[Manager] Starting SkillManager
[SkillManager] Checking for skill updates
[SkillManager] ✔ DateDayTimeYear - Version 1.0.25 in master
[SkillManager] ✔ ContextSensitive - Version 1.0.17 in master
[SkillManager] ✔ Telemetry - Version 1.1.5 in master
[SkillManager] ✔ AliceCore - Version 1.0.64 in master
[SkillManager] ✔ RedQueen - Version 1.0.24 in master
[SkillManager] Found 0 skill update(s)
[AliceSkill] Loading 2 widgets
[AliceSkill] Loaded widget "Clock"
[AliceSkill] Loaded widget "Date"
[AliceCore] Starting AliceCore skill
[SkillManager] - Started!
[SkillManager] Starting ContextSensitive skill
[SkillManager] - Started!
[SkillManager] Starting DateDayTimeYear skill
[SkillManager] - Started!
[RedQueen] Starting RedQueen skill
[SkillManager] Found existing Red Queen identity
[SkillManager] - Started!
[SkillManager] Starting Telemetry skill
[SkillManager] - Started!
[SkillManager] All skills started. 30 intents supported
[Manager] Starting DialogTemplateManager
[DialogTemplateManager] Checking data for skill "DateDayTimeYear"
[DialogTemplateManager] Checking data for skill "ContextSensitive"
[DialogTemplateManager] Checking data for skill "Telemetry"
[DialogTemplateManager] Checking data for skill "AliceCore"
[DialogTemplateManager] Checking data for skill "RedQueen"
[DialogTemplateManager] Cache uptodate
[Manager] Starting SnipsAssistantManager
[SnipsAssistantManager] Checking assistant
[SnipsAssistantManager] Assistant existing, check consistency
[SnipsAssistantManager] Assistant seems consistent
[Manager] Starting NluManager
[Manager] Starting NodeRedManager
[NodeRedManager] New scenario node found
[RedQueen] Scheduled next random speaking in 906 seconds
[main] - Started Project Alice in 10.58 seconds

**Comment by milode** [comment]
**additional Info output of aply and arecord:**
pi@ProjectAlice:~ $ aplay -l
**** Liste der Hardware-Geräte (PLAYBACK) ****
Karte 0: ALSA [bcm2835 ALSA], Gerät 0: bcm2835 ALSA [bcm2835 ALSA]
  Sub-Geräte: 7/7
  Sub-Gerät #0: subdevice #0
  Sub-Gerät #1: subdevice #1
  Sub-Gerät #2: subdevice #2
  Sub-Gerät #3: subdevice #3
  Sub-Gerät #4: subdevice #4
  Sub-Gerät #5: subdevice #5
  Sub-Gerät #6: subdevice #6
Karte 0: ALSA [bcm2835 ALSA], Gerät 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 0: ALSA [bcm2835 ALSA], Gerät 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: Dummy [Dummy], Gerät 0: Dummy PCM [Dummy PCM]
  Sub-Geräte: 8/8
  Sub-Gerät #0: subdevice #0
  Sub-Gerät #1: subdevice #1
  Sub-Gerät #2: subdevice #2
  Sub-Gerät #3: subdevice #3
  Sub-Gerät #4: subdevice #4
  Sub-Gerät #5: subdevice #5
  Sub-Gerät #6: subdevice #6
  Sub-Gerät #7: subdevice #7
Karte 2: Device [USB2.0 Device], Gerät 0: USB Audio [USB Audio]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
pi@ProjectAlice:~ $ arecord -l
**** Liste der Hardware-Geräte (CAPTURE) ****
Karte 1: Dummy [Dummy], Gerät 0: Dummy PCM [Dummy PCM]
  Sub-Geräte: 8/8
  Sub-Gerät #0: subdevice #0
  Sub-Gerät #1: subdevice #1
  Sub-Gerät #2: subdevice #2
  Sub-Gerät #3: subdevice #3
  Sub-Gerät #4: subdevice #4
  Sub-Gerät #5: subdevice #5
  Sub-Gerät #6: subdevice #6
  Sub-Gerät #7: subdevice #7

**Comment by Psychokiller1888** [comment]
Hi!
I strongly suggest to stop by on discord, as on alpha I'm not debugging those user issues on github
