### ISSUE TITLE
[BUG] - missing siteID

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#254]
To add to the todo list :)

after doing a ```sudo apt-get autoremove snips-audio-server -y``` 

on a up to date b1 of Alice, i get the following flood of  
```could not parse topic: "hermes/audioServer//audioFrame"``` errors

Alice still seems to work however it appears to slow her down considerably, restarts and project alice stops seem to be the ones suffering the most

>May 16 05:28:57 ProjectAlice python3[736]: #033[39m[NodeRedManager]          Starting#033[0m
May 16 05:28:57 ProjectAlice python3[736]: #033[39m[NodeRedManager]          New scenario node found#033[0m
May 16 05:28:57 ProjectAlice systemd[1]: Started Snips Hotword.
May 16 05:28:57 ProjectAlice snips-hotword[860]: INFO:snips_hotword_lib::universal: Loading model "/home/pi/ProjectAlice/trained/hotwords/snips_hotword", hotword_key: Some("hey_snips"), model_id: Some("workflow-hey_snips_subww_feedback_10seeds-2018_12_04T12_13_05_evaluated_model_0002")
May 16 05:28:58 ProjectAlice python3[736]: #033[39m[Project Alice]           Started in 58.53 seconds#033[0m
May 16 05:28:58 ProjectAlice python3[736]: #033[94m[AudioManager]            Playing wav stream using #033[1mdefault#033[0;94m on site id #033[1mdefault#033[0;94m#033[0m
May 16 05:29:00 ProjectAlice snips-hotword[860]: ERROR:hermes_mqtt                 : could not parse topic: "hermes/audioServer//audioFrame"
May 16 05:29:00 ProjectAlice snips-hotword[860]: ERROR:hermes_mqtt                 : could not parse topic: "hermes/audioServer//audioFrame"
May 16 05:29:00 ProjectAlice snips-hotword[860]: ERROR:hermes_mqtt                 : could not parse topic: "hermes/audioServer//audioFrame"
May 16 05:29:00 ProjectAlice snips-hotword[860]: ERROR:hermes_mqtt                 : could not parse topic: "hermes/audioServer//audioFrame"
May 16 05:29:00 ProjectAlice snips-hotword[860]: ERROR:hermes_mqtt                 : could not parse topic: "hermes/audioServer//audioFrame"

**Comment by Psychokiller1888** [comment]
Aren't those audio frames coming from a satellite?

**Comment by LazzaAU** [comment]
for those with this issue..., re installing snips-audio-server

```sudo apt-get install snips-audio-server```

 fixes the issue in the meantime until further investigations are done

**Comment by LazzaAU** [comment]
hmmmmm ....  i re installed snips-audio-server to stop the errors,
 then i seen your above message so thought i'd test that question  and therefore removed snips-audio-server again. upon restart, the previous flood of errors haven't reappeared. 4 reboots later and it's still good. Will monitor it for next couple of days but geeeeshh temperamental bloody computers  *shrug* :)

**Comment by LazzaAU** [comment]
i'm going to close this, as issue hasn't reoccured since and the issue is also currently not apparent with a clean re flashed satellite
