### ISSUE TITLE
[bug] - Satellite to Alice - key error

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#259]
On Alice b1 and Satellite version a1

**Issue**
keyError  observed and Alices crashes after hotword detected on the satellite. Ok if hotword is detected on Alice

**Test procedure** -
By using text input widget..... asking my "outside" satellite to give me the time works as expected

By using "hey snips" hotword from the satellite, the satellite responds with the "yes" im listening etc" but immediately after that **Alice** crashes with the below error log on her screen. The satellite seems to stay error free from what i can see

**Error Log** <https://paste.ubuntu.com/p/q4VVXcy5Gy/>
reboot of alice is required after this error

Figured its worth noting this error on github as i do see this type of error alot over the past three weeks of playing with the sats and this is on a fresh Sat install

**Comment by philipp2310** [comment]
I think this is fixed for a month now - but I forgot to increase the version:
https://github.com/project-alice-assistant/skill_ContextSensitive/commit/5abd1fb44a9bf95dd838d1f417d9705c1adb7cd5
Version bumped 2 days ago:
https://github.com/project-alice-assistant/skill_ContextSensitive/commit/e0546925b4e9e262d249b3fecf0d92fe9f18ce0e

could you verify that it works for you now?

Thank you!
