### ISSUE TITLE
skills: new event onDeleteSkill

### ISSUE THREAD

**Issue by poulsp** [project-alice-assistant/ProjectAlice#264]
When you delete a skill from web interface 'skill'.
It could be a good idea to have an EVENT: def onDeleteSkill(self) or something like that.
Then one could clean up all the skills mess eg. remove/delete a Skill_table.

**Comment by Psychokiller1888** [comment]
Ok, just implemented that event. Although I also implemented the database auto cleaning when a skill is deleted. Will push later today after testing

**Comment by poulsp** [comment]
Sure, you allready know.
```
[SkillManager]            - Failed to broadcast event onSkillDeleted to DialogManager: onSkillDeleted() got an unexpected keyword argument 'skillName'
```
for all broadcasts to managers and skills In 'def skillBroadcast'.

**Comment by poulsp** [comment]
```[DatabaseManager]         Failed dropping table simpleTable for component Skeleton: no such table: simpleTable```

DatabaseManaget.py 146
`cursor.execute(f'DROP TABLE {tableName}') =>  cursor.execute(f'DROP TABLE {callerName}_{tableName}')`

**Comment by philipp2310** [comment]
thanks @poulsp !
