### ISSUE TITLE
[enhancement] - update the toml

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#268]
when changing deviceName from the web UI suggest the code also changes the snips.toml from

`[snips-audio-server]
bind = "default@mqtt"
`
to 
`[snips-audio-server]
bind = "theNewDeviceName@mqtt"
`

would make for a less confusing experiance for new users perhaps ?

**Comment by Psychokiller1888** [comment]
snips audio server is not used anymore. The whole toml is soon deprecated as we are not using any of the components anymore but the hotword. The idea is to get rid of it :)

**Comment by LazzaAU** [comment]
yeah I thought that was the case too however I had to change the toml yesterday after changing the name from default to alice otherwise I heard nothing from alice. weird
