### ISSUE TITLE
AliceCore errors with fresh install 

### ISSUE THREAD

**Issue by ncoder-1** [project-alice-assistant/ProjectAlice#269]
I'm getting the follow errors after fresh install following the install instructions on a Pi 3 Model B:

```
[SkillManager] Checking for skill updates
[SkillManager] ✔ DateDayTimeYear - Version 1.0.26 in master
[SkillManager] ✔ ContextSensitive - Version 1.0.23 in master
[SkillManager] ✔ Telemetry - Version 1.1.7 in master
[SkillManager] ✔ AliceCore - Version 1.2.5 in master
[SkillManager] ✔ RedQueen - Version 1.0.24 in master
[SkillManager] Found 0 skill update(s)
[SkillManager] Couldn't import skill AliceCore.AliceCore: No module named 'core.voice.WakewordRecorder'
[AliceSkill] Loading 2 widgets
[SkillManager] Couldn't import skill DateDayTimeYear.DateDayTimeYear: No module named 'core.base.model.WidgetSizes'
[SkillManager] Starting ContextSensitive skill
[SkillManager] - Started!
[RedQueen] Starting RedQueen skill
[SkillManager] Found existing Red Queen identity
[SkillManager] - Started!
[SkillManager] Starting Telemetry skill
[SkillManager] - Started!
[SkillManager] All skills started. 9 intents supported
[Manager] Starting DialogTemplateManager
[DialogTemplateManager] Checking data for skill "DateDayTimeYear"
[DialogTemplateManager] Checking data for skill "ContextSensitive"
[DialogTemplateManager] Checking data for skill "Telemetry"
[DialogTemplateManager] Checking data for skill "AliceCore"
[DialogTemplateManager] Checking data for skill "RedQueen"
[DialogTemplateManager] Cache uptodate
[Manager] Starting SnipsAssistantManager
[SnipsAssistantManager] Checking assistant
[SnipsAssistantManager] Assistant existing, check consistency
[SnipsAssistantManager] Assistant seems consistent
[Manager] Starting NluManager
[Manager] Starting NodeRedManager
[RedQueen] Scheduled next random speaking in 1363 seconds
[main] - Started Project Alice in 13.72 seconds
```

And it never "speaks" (though audio does work manually).

In addition, the admin tab in the UI outputs the following errors:

```
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/pi/ProjectAlice/core/interface/views/AdminAuth.py", line 28, in index
    self.SkillManager.getSkillInstance('AliceCore').explainInterfaceAuth()
AttributeError: 'NoneType' object has no attribute 'explainInterfaceAuth'
```

The only thing I changed in `ProjectAlice.yaml` is the Wifi (which works) and USB microphone.

**Comment by mjlill** [comment]
There are a couple of items that need to be manually fixed to have alpha6 run.  The web ui will only be of partial service. USB mic should work okay, but if HLC was selected there will probably be an issue.  Just ask and someone will be happy to assist (including me) :)

**Comment by ncoder-1** [comment]
Hi @mjlill, thanks for the quick response.  I'll turn off HLC and try again.  Anything else I should be modifying to get up and running?

**Comment by mjlill** [comment]
You don't need to turn off the hlc, is a simple fix. There are yes a couple of things that I needed to do but the a6 is stable as a rock. Can you join the discord so others can follow?

**Comment by mjlill** [comment]
For a thumb nail guide...
nano +19 skills/AliceCore/AliceCore.py      #add the # to disable this import
#from core.voice.WakewordRecorder import WakewordRecorderState

nano  core/commons/constants.py
#check second line down must be "default", may have "office"

ls ~/ProjectAlice/skills
ls ~/ProjectAlice/skills/DateDayTimeYear
rm -rf ~/ProjectAlice/skills/DateDayTimeYear/widgets

To fix the HLC
sudo nano  /etc/systemd/system/hermesledcontrol.service
edit to make this line,  notice the "hardware="!
ExecStart=/home/pi/hermesLedControl/venv/bin/python3 main.py --hardware=googleAIY --pattern=projectalice

HLC should now be okay, restart
sudo systemctl restart hermesLedControl

also edit to the /etc/snips.toml were needed if no audio

**Comment by ncoder-1** [comment]
Thanks, I was able to comment out those lines and what not, the WakewordRecorder and DateTimeYear errosr are gone but now the error is as follows:

`[SkillManager] Couldn't import skill AliceCore.AliceCore: No module named 'core.device.model.DeviceException'`

Tried to also comment out:
`from core.device.model.DeviceException import MaxDevicePerLocationReached, MaxDeviceOfTypeReached, RequiresWIFISettings` from `AliceCore.py` but no luck either.

I'll try to join up on Discord sometime tomorrow, or maybe wait for the next release.  Thanks for the help anyway @mjlill.

**Comment by mjlill** [comment]
Oh that is a new one..  You can also maybe try upgrading to the beta, there will be some bumps of course..  Did you use master in the yaml? sounds as it may have gotten some beta stuff. There  may be some audio issues on beta

**Comment by philipp2310** [comment]
The AliceCore error is caused by a beta skill used in alpha -> either change to the beta branch for Alice(including some hotfixes that can be found in the discord channel #hotfixes ), or manually pull the latest alpha version of the AliceCore skill ([1.0.62]( https://github.com/project-alice-assistant/skill_AliceCore/tree/1.0.62_1.0.0-a6) )

**Comment by overcyber** [comment]
hiI am having the same problem when accessing the admin page of the web interface.






Can you help me ?

**Comment by overcyber** [comment]
I solved the error by updating to alpha, but now the keyboard number for the admin password does not appear

**Comment by Psychokiller1888** [comment]
Did you type admin in the textbox first? The keyboard is hidden by default

**Comment by overcyber** [comment]
Hhahaha thanks. I forgot that... It worked

**Comment by mjlill** [comment]
Depending what mic you are using, you may be best to try the advance to beta. Follow the guide in hotfixs in discord to install needed requirements, manually edit the config.py to remove some content. Send me a note if you need more details. 
The beta is working for me using a PS3Eye usb mic and a google aiy mic. Some are using the respeaker2 without problems also.  
Any feedback for other mics is welcomed. The key appears to be the  /etc/asound.conf settings.
