### ISSUE TITLE
Sanity check for device and link settings

### ISSUE THREAD

**Issue by philipp2310** [project-alice-assistant/ProjectAlice#293]
For the moment there are no checks if a device/link config input in the web UI is valid.

Example:
The roborock roomId must be numeric/int -> input can be string!

**Comment by Psychokiller1888** [comment]
I'm not sure about that. If the config is set as a "number" then you have a number field

![https://puu.sh/H8KQp.png](https://puu.sh/H8KQp.png)

**Comment by Psychokiller1888** [comment]
Oops, old bug, sry for necromancy
