### ISSUE TITLE
 saying no to  "was this what you meant" = crash

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#295]
File "/home/pi/ProjectAlice/core/util/AliceWatchManager.py", line 144, in onEndSession
    'text': f'[Dialogue] Was asked to end session with id "**{session.sessionId}**" by saying "![Yellow]({session.payload["text"]})"'
KeyError: 'text'
[9:53 PM]
Seems to come from when I say no to her "was this what you meant"
New intent detected AnswerYesOrNo with confidence 1.0
Slots
Answer -> no 
[9:55 PM]
Does it every time,  say no to when she  asks "was this what you meant"

**Comment by philipp2310** [comment]
in general I noticed today, if there is a problem (sat or main) a restart of alice on the active device is required more often than previously. without hotword is not turned on again?

**Comment by philipp2310** [comment]
One more report about alice stopping to respond after "start of a special session":
StMarco:
I was having trouble getting deep speech to work, today i booted my raspberry and before logging into the admin console i asked the time and to my surprise she understood what i asked for and replied correctly
after that i could log in to the admin console with my voice and pin but once i've logged in Alice stopped responding
the last line "I'm listening" is a response to me saying "Hey Alice" to login to the admin console, this does not get spoken

Nothing works after that, i have to restart Alice to get her working again
I'm on the master branch

**Comment by mjlill** [comment]
As an update, I am on b3 and to avoid the question which causes the crash, try reducing the number of "not understood' response to one instead of three. That seems to disable the "is that what you meant question" so you don't have say no.

**Comment by Psychokiller1888** [comment]
Hmmm... just tested:

```

[AudioManager]            Playing wav stream using default audio output from site id office (Format: 8, channels: 1, rate: 16000)
[DialogManager]           Wakeword detected on site office
[AmazonTts]               Using existing cached file 1e9c98fc50440d3b473afdbb45069c18
[AudioManager]            Playing wav stream using default audio output from site id office (Format: 8, channels: 1, rate: 16000)
[ASRManager]              Capturing come
[ASRManager]              Capturing ,
[ASRManager]              Capturing come on
[ASRManager]              Capturing Carmelo
[ASRManager]              Capturing kamaloka
[ASRManager]              Capturing call my local
[ASRManager]              Capturing Carmelo car
[ASRManager]              Capturing kamaloka
[ASRManager]              Asr captured: kamaloka
[AudioManager]            Playing wav stream using default audio output from site id office (Format: 8, channels: 1, rate: 16000)
[MqttManager]             Using probability threshold of 0.4
[MqttManager]             Intent hermes/intent/HomeAssistantSun detected but confidence score too low (0.20359719)
[AmazonTts]               Downloaded speech file a5630fe63aac3a41d3dc929274b9d4ae
[AudioManager]            Playing wav stream using default audio output from site id office (Format: 8, channels: 1, rate: 16000)
[ASRManager]              Capturing what
[ASRManager]              Capturing what time
[ASRManager]              Capturing what time is
[ASRManager]              Capturing what
[ASRManager]              Capturing what time
[ASRManager]              Capturing what time is
[ASRManager]              Capturing what time is it
[ASRManager]              Asr captured: what time is it
[AudioManager]            Playing wav stream using default audio output from site id office (Format: 8, channels: 1, rate: 16000)
[MqttManager]             Using probability threshold of 0.4
[SkillManager]            The intent "GetTime" was consumed by DateDayTimeYear
[AmazonTts]               Using existing cached file 3cfcadaba340c29dd68cb9cd62335cde
[AudioManager]            Playing wav stream using default audio output from site id office (Format: 8, channels: 1, rate: 16000)
[AmazonTts]               Using existing cached file 2b2f814349f28bdb40f5a4d6892602d1
[AudioManager]            Playing wav stream using default audio output from site id office (Format: 8, channels: 1, rate: 16000)
[ASRManager]              Capturing no
[ASRManager]              Asr captured: no
[AudioManager]            Playing wav stream using default audio output from site id office (Format: 8, channels: 1, rate: 16000)
[MqttManager]             Using probability threshold of 0.4
[SkillManager]            The intent "AnswerYesOrNo" was consumed by AliceCore
```
Same when saying yes...

Maybe you have better logs? Because unformatted your logs show nothing

**Comment by philipp2310** [comment]
had some formatted logs by marco:
the "yellow" in the original messge was the problem:
Log tried to say "session ended with text {data['text']}" but data had no text in that context

This always caused a key error I fixed by adding in "if text in data" with an else for "session ended without text"

Not closed, because I wasn't sure if this fixes all of these issues.

Currently testing for "siteId conversion", if I don't find anything related, I will close
