### ISSUE TITLE
Satellite heartbeat randomly stops

### ISSUE THREAD

**Issue by philipp2310** [project-alice-assistant/ProjectAlice#297]
![image](https://user-images.githubusercontent.com/41761223/92033506-0e46e700-ed6c-11ea-8a2e-b56866ea5ed5.png)

No recovery after this point, reboot required - reason unknown

**Comment by Psychokiller1888** [comment]
That would happen when core goes down and up again?

**Comment by philipp2310** [comment]
In that case, yes, but heartbeat never starts again.

didn't find the time to really test it yet, just wanted to archive the error message for later use, because it seems to happen from time to time (not always!)

**Comment by Psychokiller1888** [comment]
Seems like the thread cannot be joined, maybe because it tries to join... itself... I guess enclosing a try/except would solve the issue

**Comment by philipp2310** [comment]
havn't seen that error it in ages
