### ISSUE TITLE
Console evolution

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/ProjectAlice#32]
Now that managers is finally gone and SuperManager is behaving nicely and better than before, the console relies on managers too much, it needs a rethink on start

**Comment by maxbachmann** [comment]
Commands structure is now
```
list authors                          // list all authors of modules on the ProjectAliceModules repo
list modules <--authors>    // list all modules on the ProjectAliceModules (or only of all listed authors)
list intents <--module>       // list all intents that are currently installed (or only of one module)
update assistant                // downloads the newest version of the assistant
sync assistant                   // syncs the local assistant to the console
add module                       // add a new module to be installed
```

This will definetly need some more work but is at least more intuitive than it was before.

**Comment by jr-k** [comment]
I prefer the way it was before like a "namespace". Before the entity name "module" in singular form then the action "list/create". Why did you change that ?

**Comment by maxbachmann** [comment]
hm I asked @Psychokiller1888 and he said that he prefers the list module way

I agree that for modules it would make sence to give them a namespace e.g. AliceCore and then allow them to define subcommands for this namespace.

I can live both with ```list modules``` and ```module list``` even though I find the first one more intuitive, since a general goal for intuitive command line interfaces would be to build them the way you would normalways say the command in spoken language. So the question is apparently whether the prefered way is
```
list authors // list all authors of modules on the ProjectAliceModules repo
list modules <--authors> // list all modules on the ProjectAliceModules (or only of all listed authors)
list intents <--module>  // list all intents that are currently installed (or only of one module)
update assistant // downloads the newest version of the assistant
sync assistant // syncs the local assistant to the console
add module // add a new module to be installed

AliceCore <subCommands>
```

or
```
author list // list all authors of modules on the ProjectAliceModules repo
module list <--authors> // list all modules on the ProjectAliceModules (or only of all listed authors)
intent list <--module>  // list all intents that are currently installed (or only of one module)
assistant update// downloads the newest version of the assistant
assistant sync// syncs the local assistant to the console
module add// add a new module to be installed

AliceCore <subCommands>
```
right? or which interface would you like and why?

**Comment by maxbachmann** [comment]
since I found the console namespaces for modules a pretty cool idea I just added them :)
Just requires to create a file <modulename>.py in the directory console of the module with a click.group <modulename> that gets added to the command line interface. The module can add his commands to this group

**Comment by maxbachmann** [comment]
Will be reworked when the api for alice is added

**Comment by maxbachmann** [comment]
This should be tackled now that the api has all the required functions
