### ISSUE TITLE
Skill settings drop box

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#320]
In a skills settings (config.template) can we have a drop box list?  where a user can select from a known list of values

**Comment by Psychokiller1888** [comment]
you can use type `list`

**Comment by Psychokiller1888** [comment]
You have two ways to use it: https://docs.projectalice.io/skill-development/skill-configuration-file.html#the-template-file

**Comment by LazzaAU** [comment]
Ahhh. sorry didn't realise that was a option.. That's perfect works great. thanks
