### ISSUE TITLE
Abort install when yaml is not a dict

### ISSUE THREAD

**Issue by philipp2310** [project-alice-assistant/ProjectAlice#324]
stop the install and return a better understandable message

**Comment by Psychokiller1888** [comment]
It's full of hopes that I made the following test:

```
with open(test) as file:
	try:
		data = yaml.safe_load(file)
	except yaml.YAMLError:
		print('error')
	else:
		print(data)
		print(type(data))
```

With a valid yaml, no problem, data is printed and it's  a dict
With an invalid yaml, one that is missing a space, it throws, as expected, an exception.

Thought, cool, let's do that in the initialyzer! But it's already done!

```
		with Path(YAML).open(mode='r') as f:
			try:
				# noinspection PyUnboundLocalVariable
				load = yaml.safe_load(f)
				if not load:
					raise yaml.YAMLError

				initConfs = InitDict(load)
			except yaml.YAMLError as e:
				self._logger.logFatal(f'Failed loading init configurations: {e}')
				return dict()
```
So this is technically not the issue, as logFatal stops the init sequence

**Comment by philipp2310** [comment]
Closing for now - if somebody else can reproduce the exception without useful message, I'll try to fix right away
