### ISSUE TITLE
Bug in AudioServer onStop

### ISSUE THREAD

**Issue by poulsp** [project-alice-assistant/ProjectAlice#342]
Bug in AudioServer onStop

if `self.ConfigManager.getAliceConfigByName('disableSoundAndMic')` are `true` then `self._audioInputStream` are not set, that's correct.
But then in `def onStop(self)` you get an error `Error while shutting down manager AudioServer: 'NoneType' object has no attribute 'stop'` and the `snips-nlu` are never stopped.
So ` def onStop(self):` should more look like this:

```
  def onStop(self):
    super().onStop()
    if self._audioInputStream:
      self._audioInputStream.stop(ignore_errors=True)
      self._audioInputStream.close(ignore_errors=True)
    self.MqttManager.mqttClient.unsubscribe(constants.TOPIC_AUDIO_FRAME.format(self.ConfigManager.getAliceConfigByName('uuid')))
```
/@nepo

**Comment by philipp2310** [comment]
thank you!
change pushed in b5

**Comment by poulsp** [comment]
That fix looks a little suspicious.
Indent seems to be odd.
