### ISSUE TITLE
NR causing MQTT disconnects

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#353]
The nodes in NR that use AliceMQTT intermittently  go through stages of disconnect and reconnection. This seems to be a random occurance as some restarts ts ok other restarts its consistant.

What i've noticed is the code for  AliceMQTT node looks as though 
 "projectAliceInterface" should also get given a random number on the end  but in this case it doesnt seem to 

Mon Dec 21 08:16:06 2020: Client ProjectAliceInterface disconnected.
Mon Dec 21 08:16:06 2020: New connection from 127.0.0.1 on port 1883.
Mon Dec 21 08:16:06 2020: New client connected from 127.0.0.1 as ProjectAliceInterface (c1, k60).
Mon Dec 21 08:17:58 2020: Client ProjectAliceInterface disconnected.
Mon Dec 21 08:17:58 2020: New connection from 127.0.0.1 on port 1883.
Mon Dec 21 08:17:58 2020: New client connected from 127.0.0.1 as ProjectAliceInterface (c1, k60).
Mon Dec 21 08:20:26 2020: Client ProjectAliceInterface disconnected.

**Comment by philipp2310** [comment]
there shouldn't be a random number in the NR client afaik, as there must always be only one connection to NR (-> Performance! Why keep open multiple connections for the NR-Backend)

With the UI many month ago there could have been collissions between ui and NR, but with the changed client name in the UI it shouldn't happen anymore.

**Comment by philipp2310** [comment]
closing as it didn't happen for me once with heavy NR use in the last month - feel free to reopen when it happens again
