### ISSUE TITLE
Web interfaces as devices

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/ProjectAlice#364]
Putting here on paper what I dreamt last night...

### Simple version: 

Web interfaces should be AliceCore devices

### Longer version:

**WIP**

With the new UI, we added a layer of interaction with Alice, through the API.
Web interface should become Alice devices, using the same heartbeat stuff as every other devices.
The reason is rather simple:
- The interfaces get a device uid
- Other interfaces can display the interfaces states
- Interfaces, could play and or capture audio easily, if set so (you talk to Alice from your computer, no need for a sat, your computer is the satellites...)
- Alice knows where to reply to interface requests, because well, it's a device with audio capabilities....

**Comment by philipp2310** [comment]
Will edit my thoughts for this topic in here to prevent an endless growing discussion.

Privacy:
- Delete a device after loss of heartbeat (for an extended time) if "remember me" is not selected on connection

Location:
- A device always needs a parent location. For stationary devices ok, but for mobile access a new challenge.

**Comment by Psychokiller1888** [comment]
Did not think about mobiles without locations.... Well, we can make them accept no location
