### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by trapke** [project-alice-assistant/ProjectAlice#366]
Hi guys,

I installed Alice about a month ago, but other than installing a few skills and testing the wakeword, I did nothing.
Now I wanted to start Alice, but I get an error message. tail -f /var/log/syslog indicates that Alice keeps rebooting itself. Does anyone have an idea?

Here's the log from Alice itself:

[TTSManager]              Starting
[PicoTts]                 Checking dependencies
[PicoTts]                 Language from config: de-DE
[PicoTts]                 Type from config: male
[PicoTts]                 Voice from config: de-DE
[ThreadManager]           Starting
[TimeManager]             Starting
[MultiIntentManager]      Starting
[TelemetryManager]        Starting
[WebInterfaceManager]     Starting
[WebInterfaceManager]     Loaded interface in de
 * Serving Flask app "core.interface.WebInterfaceManager" (lazy loading)
[ThreadManager]           Started new thread WebInterface, thread count: 5
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
[AliceWatchManager]       Starting
[DialogManager]           Starting
[WakewordManager]         Starting
[SnipsWakeword]           Checking dependencies
[SnipsWakeword]           Starting Snips hotword
[TalkManager]             Starting
[NluManager]              Starting
[SkillManager]            Starting
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 101, in onStart
    skillManager.onStart()
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 81, in onStart
    self._skillList = self._loadSkills()
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 144, in _loadSkills
    installer = json.loads(Path(self.Commons.rootDir(), f'skills/{skill["skillName"]}/{skill["skillName"]}.install').read_text())
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error while starting managers: Expecting value: line 1 column 1 (char 0)
[Project Alice]           Shutting down
Error while shutting down manager unknownManager: 'MqttManager'
[Project Alice]           Started in 22.19 seconds
[Project Alice]           Shutting down
Error while shutting down manager unknownManager: 'MqttManager'
[Project Alice]           Shutdown completed, see you soon!

**Comment by Psychokiller1888** [comment]
Hi

Did you create a skill? Or install any other than the default ones? This is a skill installer issue

**Comment by trapke** [comment]
Thanks for the fast response! I didn't create a custom skill, only installed some from the skill site. Is it somehow possible to delete all of them via file operations?

Skills I have installed: 
SpeechVisualizer
Reminder
And maybe TextInputWidget

**Comment by Psychokiller1888** [comment]
No you can't delete those in one operation. But you can go to `~/ProjectAlice/skills/` and `rm -rf SpeechVisualizer` one by one and start Alice, to find the one causing problem

**Comment by trapke** [comment]
I had RedQueen installed as well, I deleted that and now it works. Thank you!
