### ISSUE TITLE
OWM currently has no instructions

### ISSUE THREAD

**Issue by philipp2310** [project-alice-assistant/ProjectAlice#367]
There are currently no instructions for OWM, would be nice to have instructions with a link to the page where you get your api key

**Comment by Psychokiller1888** [comment]
EN is done

**Comment by philipp2310** [comment]
solved with [https://github.com/project-alice-assistant/skill_OpenWeatherMap/commit/e9223af8c06ad20a2dff1823c3d66b152ca2c37d](https://github.com/project-alice-assistant/skill_OpenWeatherMap/commit/e9223af8c06ad20a2dff1823c3d66b152ca2c37d)
