### ISSUE TITLE
Updates that add dependencies

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/ProjectAlice#370]
We add and remove dependencies, being PIP or system. Exemple with latest merge of new ui is the addition of cssmin, htmlmin and jsmin as well as nhinx server on system side.

We need a way for Alice to auto add them, at least for users jumping from B4 to B5. This is what I thought

- Add a DB table, from manager ProjectAlice
- Store the latest Alice version the user is running. Alice starts with b4? Write it!
- If Alice updates to b5, she'll know she was on b4 last boot, so we can make sure to run the PIP reqs and system reqs.
- Why not store additional steps in db, like b4 to b5 => drop table XXX per exemple

**Comment by philipp2310** [comment]
Quite an important feature - especially while the features get added at the current speed :)

Are the versions required for that? If a new dependency is added in the middle of b5 development, we could get rid of the #hotfixes by updating the dependencies as well!

Without Versions:
- DB holds currently installed pip/sys
- on boot: check pip/sys table against new requirements.txt
- install and uninstall all changes, update the DB
(technically you could check the requirements against the system on every boot, without remembering yourself what is already instaled, but that should be slower I guess)

About the DB changes:
A much more complex feature.. ideally it would prevent any data loss if possible. not yet sure how it could be better than your current implementation - apart from manually programming every DB change and its consequences
