### ISSUE TITLE
add user doesnt work 

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#374]
Issue : add user from the interface doesn't work.

AliceSkill.py had client= rather than deviceUid= as parameter... that has been fixed and pushed however

when it progresses to calling AddNewUser there is no session.deviceId so eventually fails in AliceWatch at ```def onSessionStarted(self, session: DialogSession):```

```[CommonsManager]          * DEV METHOD TRACING CODE *
[CommonsManager]          The calling method to get to 'ask' was 'addNewUser' in file '/home/pi/ProjectAlice/skills/AliceCore/AliceCore.py' on line '232'
[CommonsManager]          Other calls to get to 'addNewUser' were 'addUser' method, and before that was 'inner'
[CommonsManager]          'deviceUid' has a value of 'None' 
[CommonsManager]          
[CommonsManager]          Remember to remove this devCode from '/home/pi/ProjectAlice/core/base/model/AliceSkill.py' line '591'
```
adding  to aliceWatch...

```	
def onSessionStarted(self, session: DialogSession):
		if not session.deviceUid:
			session.deviceUid = self.DeviceManager.getMainDevice().uid 
```

fixes the issue. but suspect that isn't the correct approach and maybe missing the deviceID from the ui call ? *shrug*

**Comment by Psychokiller1888** [comment]
Fixed yesterday
