### ISSUE TITLE
dialog view bug ?

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#400]
Possibly a known bug as i believe its still WIP ?.....

Purposely type into dialog view the incorrectly spelt intent such as :

"what is the tme"
- alice doesnt recognise it (as expected)

However, any further interaction is not understood unless the session times out first. Is fine via voice

see attached 
![Kazam_screenshot_00021](https://user-images.githubusercontent.com/31381872/108463693-91340d80-72ca-11eb-85c1-60678a8debe9.png)

**Comment by philipp2310** [comment]
shouldn't be an UI issue directly, but API for continueSession
