### ISSUE TITLE
Uninstalling a module

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/ProjectAlice#42]
Uninstalling a module is required!

- ~~Removes the settings in config.py~~
- ~~Removes the files in modules/~~
- Removes the entries in samkilla
- Removes the skill/intents/slots from the assistant
- ~~Syncs/trains/downloads/install the assistant~~

**Comment by maxbachmann** [comment]
I will add this to the cli aswell

**Comment by Psychokiller1888** [comment]
As of now the config is eliminated and the intents deactivated. The rest is TODO

**Comment by maxbachmann** [comment]
yeah at least for me the sync function from the cli fails aswell. Not really sure why since I guess it should be used in a similar way already by the initialiser

**Comment by Psychokiller1888** [comment]
Can we get an ETA on this please??

**Comment by Psychokiller1888** [comment]
@jr-k Halloooo?
