### ISSUE TITLE
NR theme and node failure

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#436]
During a new install, i've noticed NR sometimes fails to install the dark theme, she also on occasions has failed to configure the alice nodes and i have to go to the pallette to enable them. For me the theme part has happened at least 4 times. Other reported cases of this in discord also but they choose not to add a github issue :).

**Suspected cause**

I feel the issue lays with user/alice rebooting during final stages of the NR configuration.

**My thoughts**

NR can take a little while to install and its possible Alice gets rebooted before NR has been configured fully due to user forgetting NR is still doing it's thing in the background ?. 
Senario i suspect is the  "package.json" file gets installled and is part way through the remaining code when alice is potentially restarted ? So now on startup Alice see's package.json file and therefore believes NR is all good to go so ignores the rest of the code despite settings.js file not being properly configured.

**Potential Remedy **

Are you happy for me to add a boolean in config.json called  ```nodeRedConfigured = false``` . then check that key on restart... if False, re run ```configureNewNodeRed(self)``` if True ignore ?

**Comment by Psychokiller1888** [comment]
Hmmm, I'd rather make the node red install run on the main thread, so it blocks any further instructions and Alice doesn't reboot while it is installing it

**Comment by LazzaAU** [comment]
i did appear to fix the theme side of it by adding a json file in system/nodeRed. 

if key in json file = false, apon second restart and package.json file exists, then reconfigure NR during bootup, else do nothing

However looks like your all over it so will leave it alone :)

**Comment by philipp2310** [comment]
continued in #617
