### ISSUE TITLE
snips goes into defunct mode

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#446]
Randomly my Alice stops listening, and as reported in discord, snips-hotword goes into defunct. Haven't had time to investigate or determine a trigger yet. have only noticed it in rc1

![Kazam_screenshot_00030](https://user-images.githubusercontent.com/31381872/118551272-14b5ab80-b7a1-11eb-8460-82dfa948b7c5.png)

**Comment by Psychokiller1888** [comment]
What does "defunct" really mean? By that I wonder what that state really is

**Comment by philipp2310** [comment]
would be good if you can close this issue when the error seems to have disappeared :)

My tests with killing the processes worked fine, but you never know if there are more factors in this!

**Comment by LazzaAU** [comment]
been two days now and i havent noticed the defunct message :+1: happy to close issue if no further reports
