### ISSUE TITLE
snips console duplicates

### ISSUE THREAD

**Issue by maxbachmann** [project-alice-assistant/ProjectAlice#45]
I removed my local assistant file that was generated in var/assistants/en/pro_* 
then synced it again using SamKilla. This caused every intent to be created a second time in the console

**Comment by Psychokiller1888** [comment]
Yep, slots too

**Comment by jr-k** [comment]
@maxbachmann you always used "EN" to generate the assistant ? Snips console allows multiple intent with same name but only if the language is different

**Comment by maxbachmann** [comment]
yes I did only create english

**Comment by jr-k** [comment]
Is this issue still relevant ? Are you able to make this happen with the current alpha2 build. If yes can you give me some details ?

**Comment by Psychokiller1888** [comment]
Looks like it's still the case

https://github.com/project-alice-powered-by-snips/ProjectAlice/issues/72
