### ISSUE TITLE
AutoBugReporting error and deviceManager issue 

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#607]
i got the below devicemanager and myHomeApi errors which in turn triggered the bug reporting ? however, at the time i had crap internet so had fallen offline which then gave errors for bug reporting.

Granted my bug reporting is still not working correctly but did make me think... will the bug reporting error like this if the user is "offline" ? if so maybe need to account for that ? just a thought 

>[Initializer]                       Starting Project Alice initialization
[PreInitializer]                    No initialization needed
[Project Alice]                     Starting Alice main unit
[BugReportManager]                  Initializing
[BugReportManager]                  Flag file detected, recording errors for this run
[BugReportManager]                  Project Alice logs
[BugReportManager]                  Git commit id: 20bb740b15ddcac2756636bc24b25b375a89e532
[CommonsManager]                    Initializing
[StateManager]                      Initializing
[SubprocessManager]                 Initializing
[ConfigManager]                     Initializing
[ConfigManager]                     Checking Alice configuration file
[DatabaseManager]                   Initializing
[SkillManager]                      Initializing
[WidgetManager]                     Initializing
[DeviceManager]                     Initializing
[AudioManager]                      Initializing
[LanguageManager]                   Initializing
[LanguageManager]                   Active language set to en-US
[LanguageManager]                   Default language set to en-US
[ASRManager]                        Initializing
[TTSManager]                        Initializing
[ThreadManager]                     Initializing
[MqttManager]                       Initializing
[TimeManager]                       Initializing
[UserManager]                       Initializing
[MultiIntentManager]                Initializing
[TelemetryManager]                  Initializing
[LocationManager]                   Initializing
[InternetManager]                   Initializing
[WakewordRecorder]                  Initializing
[TalkManager]                       Initializing
[WebUIManager]                      Initializing
[ApiManager]                        Initializing
[NodeRedManager]                    Initializing
[SkillStoreManager]                 Initializing
[DialogTemplateManager]             Initializing
[AssistantManager]                  Initializing
[NluManager]                        Initializing
[AliceWatchManager]                 Initializing
[DialogManager]                     Initializing
[WakewordManager]                   Initializing
[WebUINotificationManager]          Initializing
[BugReportManager]                  Starting
[CommonsManager]                    Starting
[StateManager]                      Starting
[ThreadManager]                     Started new thread subprocessManager, thread count: 1
[ConfigManager]                     Starting
[LanguageManager]                   Starting
[WebUINotificationManager]          Starting
[LocationManager]                   Starting
[LocationManager]                   Loaded location Home
[LocationManager]                   Loaded location Outside
[LocationManager]                   Loaded location Bedroom
[LocationManager]                   Loaded location Bathroom
[LocationManager]                   Loaded location Inside
[LocationManager]                   Loaded location Entrance
[LocationManager]                   Loaded location Lounge
[LocationManager]                   Loaded location Kitchen
[LocationManager]                   Loaded location StoreRoom
[LocationManager]                   Loaded location Ute
[LocationManager]                   Loaded 10 locations
[AudioManager]                      Starting
[AudioManager]                      Using seeed-4mic-voicecard: bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0 (hw:1,0) for audio input
[AudioManager]                      Using bcm2835 Headphones: - (hw:0,0) for audio output
[InternetManager]                   Starting
[ThreadManager]                     Started new thread internetCheckThread, thread count: 3
[DatabaseManager]                   Starting
[UserManager]                       Starting
[UserManager]                       Loaded 3 users
[MqttManager]                       Starting
[AliceWatchManager]                 Starting
[ApiManager]                        Starting
 * Serving Flask app 'core.webApi.ApiManager' (lazy loading)
[ThreadManager]                     Started new thread API, thread count: 5
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
[ASRManager]                        Starting
   Use a production WSGI server instead.
 * Debug mode: on
[GoogleAsr]                         Checking dependencies
[GoogleAsr]                         Starting Google Asr
[DialogManager]                     Starting
[MultiIntentManager]                Starting
[SkillStoreManager]                 Starting
[TelemetryManager]                  Starting
[ThreadManager]                     Starting
[TimeManager]                       Starting
[TTSManager]                        Starting
[AmazonTts]                         Checking dependencies
[AmazonTts]                         Language from config: en-GB
[AmazonTts]                         Type from config: female
[AmazonTts]                         Voice from config: Amy
[WakewordManager]                   Starting
[SnipsWakeword]                     Checking dependencies
[SnipsWakeword]                     Starting Snips hotword
[SubprocessManager]                 Starting the subprocess SnipsHotword
[WebUIManager]                      Starting
[WebUIManager]                      Started nginx server
[ThreadManager]                     Started new thread DisplayResourceUsage, thread count: 6
[TalkManager]                       Starting
[NluManager]                        Starting
[SkillManager]                      Starting
[SkillManager]                      Checking for skill updates
[SkillManager]                      AliceCore - Version 1.5.25 in rc
[SkillManager]                      Skill AliceDevTools is not available on Github. Deprecated or is it a dev skill?
[DeviceManager]                     Waiting for DeviceManager (1)
[DeviceManager]                     Waiting for DeviceManager (2)
[DeviceManager]                     Waiting for DeviceManager (3)
[DeviceManager]                     Waiting for DeviceManager (4)
[DeviceManager]                     Waiting for DeviceManager (5)
[SkillManager]                      AliceVolume - Version 1.0.14 in rc
[DeviceManager]                     Waiting for DeviceManager (6)
[SkillManager]                      BackUpAlice - Version 1.1.10 in rc
[SkillManager]                      ContextSensitive - Version 1.0.33 in rc
[SkillManager]                      DateDayTimeYear - Version 1.1.3 in rc
[SkillManager]                      HLCpattern - Version 1.1.4 in rc
[SkillManager]                      HomeAssistant - Version 3.1.8 in rc - Locked for local changes!
[SkillManager]                      RedQueen - Version 1.0.40 in rc - Locked for local changes!
[SkillManager]                      Reminder - Version 1.2.4 in rc
[DeviceManager]                     Waiting for DeviceManager (7)
[DeviceManager]                     Waiting for DeviceManager (8)
[DeviceManager]                     Waiting for DeviceManager (9)
[DeviceManager]                     Waiting for DeviceManager (10)
[DeviceManager]                     Waiting for DeviceManager (11)
[SkillManager]                      Telegram - Version 1.5.4 in rc
[DeviceManager]                     Waiting for DeviceManager (12)
[SkillManager]                      Telemetry - Version 1.3.5 in rc
[SkillManager]                      Skill WaterTankLevel is not available on Github. Deprecated or is it a dev skill?
[SkillManager]                      Found 0 skill update
[ConfigManager]                     Checking configuration for skill AliceCore
[ConfigManager]                     Checking configuration for skill AliceDevTools
[ConfigManager]                     Checking configuration for skill AliceVolume
[ConfigManager]                     Checking configuration for skill BackUpAlice
[DeviceManager]                     Waiting for DeviceManager (13)
[ConfigManager]                     Checking configuration for skill ContextSensitive
[DeviceManager]                     Waiting for DeviceManager (14)
[DeviceManager]                     Waiting for DeviceManager (15)
[DeviceManager]                     Waiting for DeviceManager (16)
[DeviceManager]                     Waiting for DeviceManager (17)
[DeviceManager]                     Waiting for DeviceManager (18)
[ConfigManager]                     Checking configuration for skill DateDayTimeYear
[ConfigManager]                     Checking configuration for skill HLCpattern
[ConfigManager]                     Checking configuration for skill HomeAssistant
[ConfigManager]                     Checking configuration for skill RedQueen
[ConfigManager]                     Checking configuration for skill Reminder
[ConfigManager]                     Checking configuration for skill Telegram
[ConfigManager]                     Checking configuration for skill Telemetry
[DeviceManager]                     Waiting for DeviceManager (19)
[ConfigManager]                     Checking configuration for skill WaterTankLevel
[DeviceManager]                     Waiting for DeviceManager (20)
[AliceCore]                         Starting
[AliceCore]                         Found 2 device type
[AliceCore]                         Started!
[AliceDevTools]                     Starting
[AliceDevTools]                     Started!
[AliceVolume]                       Starting
[DeviceManager]                     Waiting for DeviceManager (21)
[DeviceManager]                     Waiting for DeviceManager (22)
[DeviceManager]                     Waiting for DeviceManager (23)
[DeviceManager]                     Impossible to find device instance for id/uid 71/None, skipping
[DeviceManager]                     Impossible to find device instance for id/uid 72/None, skipping
[DeviceManager]                     Impossible to find device instance for id/uid 71/None, skipping
[MyHomeApi]                         Failed to retrieve icon for device id 71 (error while getting filename) :'NoneType' object has no attribute 'getDeviceIcon'
[MyHomeApi]                         Failed to retrieve icon for device id 72 (error while getting filename) :'NoneType' object has no attribute 'getDeviceIcon'
[MyHomeApi]                         Failed to retrieve icon for device id 71 (error while getting filename) :'NoneType' object has no attribute 'getDeviceIcon'
[AliceVolume]                       Started!
[Traceback]                         Traceback (most recent call last):
[Traceback]                         Traceback (most recent call last):
[BackUpAlice]                       Starting
[Traceback]                           File "/home/pi/ProjectAlice/core/webApi/model/MyHomeApi.py", line 333, in getDeviceIcon
[Traceback]                           File "/home/pi/ProjectAlice/core/webApi/model/MyHomeApi.py", line 333, in getDeviceIcon
[DeviceManager]                     Waiting for DeviceManager (1)
[Traceback]                         Traceback (most recent call last):
[Traceback]                             file = device.getDeviceIcon()
[Traceback]                             file = device.getDeviceIcon()
[Traceback]                           File "/home/pi/ProjectAlice/core/webApi/model/MyHomeApi.py", line 333, in getDeviceIcon
[Traceback]                         AttributeError: 'NoneType' object has no attribute 'getDeviceIcon'
[Traceback]                         AttributeError: 'NoneType' object has no attribute 'getDeviceIcon'
[BackUpAlice]                       Started!
[Traceback]                             file = device.getDeviceIcon()
[Traceback]                         AttributeError: 'NoneType' object has no attribute 'getDeviceIcon'
[ContextSensitive]                  Starting
[ContextSensitive]                  Started!
[DateDayTimeYear]                   Starting
[DateDayTimeYear]                   Found 2 widgets
[DateDayTimeYear]                   No widget config template for widget type Clock found
[DateDayTimeYear]                   No widget config template for widget type Date found
[DateDayTimeYear]                   Started!
[HLCpattern]                        Starting
[HLCpattern]                        Started!
[HomeAssistant]                     Starting
[HomeAssistant]                     Found 10 device type
[HomeAssistant]                     Started!
[RedQueen]                          Starting
[RedQueen]                          Started!
[RedQueen]                          Found existing Red Queen identity
[Reminder]                          Starting
[Reminder]                          Started!
[Reminder]                          Doing database maintenance
[Reminder]                          Checking for active timers in MyReminders database
[Reminder]                          Checking for active timers in MyTimer database
[Reminder]                          Checking for active timers in MyAlarm database
[Telegram]                          Starting
[Telegram]                          Started!
[DeviceManager]                     Waiting for DeviceManager (2)
[DeviceManager]                     Waiting for DeviceManager (3)
[DeviceManager]                     Waiting for DeviceManager (4)
[DeviceManager]                     Waiting for DeviceManager (5)
[DeviceManager]                     Waiting for DeviceManager (6)
[DeviceManager]                     Waiting for DeviceManager (7)
[DeviceManager]                     Waiting for DeviceManager (8)
[DeviceManager]                     Waiting for DeviceManager (9)
[DeviceManager]                     Waiting for DeviceManager (10)
[DeviceManager]                     Waiting for DeviceManager (11)
[DeviceManager]                     Waiting for DeviceManager (12)
[DeviceManager]                     Waiting for DeviceManager (13)
[DeviceManager]                     Waiting for DeviceManager (14)
[DeviceManager]                     Waiting for DeviceManager (15)
[DeviceManager]                     Waiting for DeviceManager (16)
[DeviceManager]                     Waiting for DeviceManager (17)
[DeviceManager]                     Waiting for DeviceManager (18)
[DeviceManager]                     Waiting for DeviceManager (19)
[DeviceManager]                     Waiting for DeviceManager (20)
[DeviceManager]                     Waiting for DeviceManager (21)
[DeviceManager]                     Impossible to find device instance for id/uid 73/None, skipping
[DeviceManager]                     Waiting for DeviceManager (22)
[MyHomeApi]                         Failed to retrieve icon for device id 73 (error while getting filename) :'NoneType' object has no attribute 'getDeviceIcon'
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/core/webApi/model/MyHomeApi.py", line 333, in getDeviceIcon
[Traceback]                             file = device.getDeviceIcon()
[Traceback]                         AttributeError: 'NoneType' object has no attribute 'getDeviceIcon'
[DeviceManager]                     Waiting for DeviceManager (1)
[DeviceManager]                     Waiting for DeviceManager (2)
[DeviceManager]                     Waiting for DeviceManager (3)
[DeviceManager]                     Waiting for DeviceManager (4)
[DeviceManager]                     Waiting for DeviceManager (5)
[DeviceManager]                     Waiting for DeviceManager (6)
[DeviceManager]                     Waiting for DeviceManager (7)
[DeviceManager]                     Waiting for DeviceManager (8)
[DeviceManager]                     Waiting for DeviceManager (9)
[DeviceManager]                     Waiting for DeviceManager (10)
[DeviceManager]                     Waiting for DeviceManager (11)
[DeviceManager]                     Waiting for DeviceManager (12)
[Telegram]                          Loaded 1 user
[Telemetry]                         Starting
[Telemetry]                         Started!
[WaterTankLevel]                    Starting
[WaterTankLevel]                    Started!
[SkillManager]                      Skills started. 60 intents supported
[DeviceManager]                     Starting
[DeviceManager]                     Loaded 60 device instance
[WidgetManager]                     Starting
[WidgetManager]                     Loaded 2 pages
[WidgetManager]                     Loaded 2 templates from 1 skill
[WidgetManager]                     Loaded 1 active widget
[DialogTemplateManager]             Starting
[AssistantManager]                  Starting
[AssistantManager]                  Checking assistant
[AssistantManager]                  Assistant seems consistent
[DialogTemplateManager]             Checking data for skill AliceCore
[DialogTemplateManager]             Checking data for skill AliceDevTools
[DialogTemplateManager]             Checking data for skill AliceVolume
[DialogTemplateManager]             Checking data for skill BackUpAlice
[DialogTemplateManager]             Checking data for skill ContextSensitive
[DialogTemplateManager]             Checking data for skill DateDayTimeYear
[DialogTemplateManager]             Checking data for skill HLCpattern
[DialogTemplateManager]             Checking data for skill HomeAssistant
[DialogTemplateManager]             Checking data for skill RedQueen
[DialogTemplateManager]             Checking data for skill Reminder
[DialogTemplateManager]             Checking data for skill Telegram
[DialogTemplateManager]             Checking data for skill Telemetry
[DialogTemplateManager]             Checking data for skill WaterTankLevel
[DialogTemplateManager]             Cache uptodate
[NodeRedManager]                    Starting
[AudioManager]                      Starting audio publisher
[ThreadManager]                     Started new thread audioPublisher, thread count: 14
[ThreadManager]                     Started new thread checkHeartbeats, thread count: 16
[ThreadManager]                     Started new thread heartBeatThread-1639812644, thread count: 16
[HomeAssistant]                     HomeAssistant Connected
[HomeAssistant]                     Sending Heartbeat connection requests
[DeviceManager]                     Device named 240 power in the StoreRoom connected
[DeviceManager]                     Device named diesel heater on in the StoreRoom connected
[DeviceManager]                     Device named laptop charger in the StoreRoom connected
[DeviceManager]                     Device named ute power in the StoreRoom connected
[DeviceManager]                     Device named pillow light in the StoreRoom connected
[DeviceManager]                     Device named main light in the StoreRoom connected
[DeviceManager]                     Device named entrance light in the StoreRoom connected
[DeviceManager]                     Device named rainwatervalve in the StoreRoom connected
[DeviceManager]                     Device named external light in the StoreRoom connected
[DeviceManager]                     Device named pillow light in the StoreRoom connected
[DeviceManager]                     Device named awning light in the StoreRoom connected
[DeviceManager]                     Device named couch light in the StoreRoom connected
[DeviceManager]                     Device named window light in the StoreRoom connected
[DeviceManager]                     Device named witi in the StoreRoom connected
[DeviceManager]                     Device named sink light in the StoreRoom connected
[DeviceManager]                     Device named awning light in the StoreRoom connected
[DeviceManager]                     Device named window light in the StoreRoom connected
[DeviceManager]                     Device named couch light in the StoreRoom connected
[DeviceManager]                     Device named round lights in the StoreRoom connected
[DeviceManager]                     Device named toilet light in the StoreRoom connected
[DeviceManager]                     Device named mirror light in the StoreRoom connected
[DeviceManager]                     Device named external light in the StoreRoom connected
[DeviceManager]                     Device named kitchen lights in the StoreRoom connected
[DeviceManager]                     Device named bedroom lights in the StoreRoom connected
[DeviceManager]                     Device named bathroom lights in the StoreRoom connected
[DeviceManager]                     Device named lounge lights in the StoreRoom connected
[DeviceManager]                     Device named outside lights in the StoreRoom connected
[DeviceManager]                     Device named all main lights in the StoreRoom connected
[DeviceManager]                     Device named fridge fan in the StoreRoom connected
[DeviceManager]                     Device named heater state in the StoreRoom connected
[DeviceManager]                     Device named alarm in the StoreRoom connected
[DeviceManager]                     Device named people home in the StoreRoom connected
[DeviceManager]                     Device named awning switch - on is open in the StoreRoom connected
[DeviceManager]                     Device named rain water hose connected in the StoreRoom connected
[DeviceManager]                     Device named rain water low level in the StoreRoom connected
[DeviceManager]                     Device named rain water mid level in the StoreRoom connected
[DeviceManager]                     Device named rain water high level in the StoreRoom connected
[DeviceManager]                     Device named rain water pump running in the StoreRoom connected
[DeviceManager]                     Device named diesel heater off in the StoreRoom connected
[DeviceManager]                     Device named rain water pump in the StoreRoom connected
[DeviceManager]                     Device named rain water tank in the StoreRoom connected
[DeviceManager]                     Device named fresh water tank 1 in the StoreRoom connected
[DeviceManager]                     Device named fresh water tank 2 in the StoreRoom connected
[DeviceManager]                     Device named grey water tank 1 in the StoreRoom connected
[DeviceManager]                     Device named toilet motion in the StoreRoom connected
[DeviceManager]                     Device named ute rear battery voltage in the StoreRoom connected
[DeviceManager]                     Device named ute rear battery current in the StoreRoom connected
[DeviceManager]                     Device named ute rear battery power in the StoreRoom connected
[DeviceManager]                     Device named inside temperature in the StoreRoom connected
[DeviceManager]                     Device named inside humidity in the StoreRoom connected
[DeviceManager]                     Device named inside dewpoint in the StoreRoom connected
[DeviceManager]                     Device named inside pressure in the StoreRoom connected
[DeviceManager]                     Device named inside gas in the StoreRoom connected
[DeviceManager]                     Device named outside temperature bme280 temperature in the StoreRoom connected
[DeviceManager]                     Device named outside temperature bme280 humidity in the StoreRoom connected
[DeviceManager]                     Device named outside temperature bme280 dewpoint in the StoreRoom connected
[DeviceManager]                     Device named outside temperature bme280 pressure in the StoreRoom connected
[DeviceManager]                     Device WebInterface has not given a signal since 5 seconds or more
[SnipsNlu]                          Starting Snips NLU
[SubprocessManager]                 Starting the subprocess SnipsNLU
[DeviceManager]                     Device WebInterface has not given a signal since 5 seconds or more
[ASRManager]                        Internet lost, switching to offline Asr
[GoogleAsr]                         Stopping Google Asr
[GoogleAsr]                         Checking dependencies
[ASRManager]                        Asr did not satisfy the user settings, falling back to coqui
[CoquiAsr]                          Checking dependencies
[CoquiAsr]                          Starting Coqui Asr
[Project Alice]                     Started in 73.44 seconds
[AudioManager]                      Playing wav stream using bcm2835 Headphones: - (hw:0,0) audio output from device Alice (channels: 1, rate: 16000)
[AudioManager]                      Playing bytes finished
[CoquiAsr]                          Loading Model
TensorFlow: v2.3.0-6-g23ad988fcde
 Coqui STT: v0.10.0-alpha.4-78-g1f3d2dab
[CoquiAsr]                          Model Loaded
[CoquiAsr]                          Scorer Loaded
[CoquiAsr]                          Starting Coqui Asr
[CoquiAsr]                          Loading Model
TensorFlow: v2.3.0-6-g23ad988fcde
 Coqui STT: v0.10.0-alpha.4-78-g1f3d2dab
[CoquiAsr]                          Model Loaded
[CoquiAsr]                          Scorer Loaded
[TTSManager]                        Internet lost, switching to offline TTS
[PicoTts]                           Checking dependencies
[PicoTts]                           Language from config: en-GB
[PicoTts]                           Type from config: female
[PicoTts]                           Voice from config: Amy
[TTSManager]                        Tts failed starting: None
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/core/base/ConfigManager.py", line 363, in writeToAliceConfigurationFile
[Traceback]                             self.CONFIG_FILE.write_text(json.dumps(sort, indent='\t', sort_keys=True))
[Traceback]                           File "/usr/lib/python3.7/json/init.py", line 238, in dumps
[Traceback]                             **kw).encode(obj)
[Traceback]                           File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
[Traceback]                             chunks = list(chunks)
[Traceback]                           File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
[Traceback]                             yield from _iterencode_dict(o, _current_indent_level)
[Traceback]                           File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
[Traceback]                             yield from chunks
[Traceback]                           File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
[Traceback]                             o = _default(o)
[Traceback]                           File "/usr/lib/python3.7/json/encoder.py", line 179, in default
[Traceback]                             raise TypeError(f'Object of type {o.class.name} '
[Traceback]                         TypeError: Object of type set is not JSON serializable
[Traceback]                         During handling of the above exception, another exception occurred:
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/core/voice/TTSManager.py", line 107, in _loadTTS
[Traceback]                             self._tts.onStart()
[Traceback]                           File "/home/pi/ProjectAlice/core/voice/model/Tts.py", line 98, in onStart
[Traceback]                             self.ConfigManager.updateAliceConfiguration(key='ttsType', value={self._type})
[Traceback]                           File "/home/pi/ProjectAlice/core/base/ConfigManager.py", line 246, in updateAliceConfiguration
[Traceback]                             self.writeToAliceConfigurationFile()
[Traceback]                           File "/home/pi/ProjectAlice/core/base/ConfigManager.py", line 365, in writeToAliceConfigurationFile
[Traceback]                             raise ConfigurationUpdateFailed()
[Traceback]                         core.ProjectAliceExceptions.ConfigurationUpdateFailed: None
[Project Alice]                     Shutting down
[SkillManager]                      Stopping
[AliceCore]                         Stopped
[AliceDevTools]                     Stopped
[AliceVolume]                       Stopped
[BackUpAlice]                       Stopped
[ContextSensitive]                  Stopped
[DateDayTimeYear]                   Stopped
[HLCpattern]                        Stopped
[HomeAssistant]                     Backing up dialog file
[HomeAssistant]                     Stopped
[RedQueen]                          Stopped
[Reminder]                          Stopped
[Telegram]                          Stopped
[Telemetry]                         Stopped
[WaterTankLevel]                    Stopped
[AliceWatchManager]                 Stopping
[ApiManager]                        Stopping
[CoquiAsr]                          Stopping Coqui Asr
[DialogManager]                     Stopping
[MultiIntentManager]                Stopping
[SkillStoreManager]                 Stopping
[TelemetryManager]                  Stopping
[ThreadManager]                     Stopping
[TimeManager]                       Stopping
[TTSManager]                        Stopping
[WakewordManager]                   Stopping
[SnipsWakeword]                     Stopping Snips hotword
[WebUIManager]                      Stopping
[WebUIManager]                      Stopped nginx server
[ConfigManager]                     Stopping
[AudioManager]                      Stopping
[LanguageManager]                   Stopping
[LocationManager]                   Stopping
[DeviceManager]                     Stopping
[ThreadManager]                     Terminated thread heartBeatThread-1639812644, thread count: 13
[TalkManager]                       Stopping
[DatabaseManager]                   Stopping
[UserManager]                       Stopping
[WebUINotificationManager]          Stopping
[WidgetManager]                     Stopping
[DialogTemplateManager]             Stopping
[AssistantManager]                  Stopping
[NluManager]                        Stopping
[SnipsNlu]                          Stopping Snips NLU
[InternetManager]                   Stopping
[NodeRedManager]                    Stopping
[StateManager]                      Stopping
[SubprocessManager]                 Stopping
[MqttManager]                       Stopping
[BugReportManager]                  Stopping
[Project Alice Logger]              Error stopping BugReportManager: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/project-alice-assistant/ProjectAlice/issues (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x62d8f5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/core/base/ConfigManager.py", line 363, in writeToAliceConfigurationFile
[Traceback]                             self.CONFIG_FILE.write_text(json.dumps(sort, indent='\t', sort_keys=True))
[Traceback]                           File "/usr/lib/python3.7/json/init.py", line 238, in dumps
[Traceback]                             **kw).encode(obj)
[Traceback]                           File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
[Traceback]                             chunks = list(chunks)
[Traceback]                           File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
[Traceback]                             yield from _iterencode_dict(o, _current_indent_level)
[Traceback]                           File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
[Traceback]                             yield from chunks
[Traceback]                           File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
[Traceback]                             o = _default(o)
[Traceback]                           File "/usr/lib/python3.7/json/encoder.py", line 179, in default
[Traceback]                             raise TypeError(f'Object of type {o.class.name} '
[Traceback]                         TypeError: Object of type set is not JSON serializable
[Traceback]                         During handling of the above exception, another exception occurred:
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/core/voice/TTSManager.py", line 107, in _loadTTS
[Traceback]                             self._tts.onStart()
[Traceback]                           File "/home/pi/ProjectAlice/core/voice/model/Tts.py", line 98, in onStart
[Traceback]                             self.ConfigManager.updateAliceConfiguration(key='ttsType', value={self._type})
[Traceback]                           File "/home/pi/ProjectAlice/core/base/ConfigManager.py", line 246, in updateAliceConfiguration
[Traceback]                             self.writeToAliceConfigurationFile()
[Traceback]                           File "/home/pi/ProjectAlice/core/base/ConfigManager.py", line 365, in writeToAliceConfigurationFile
[Traceback]                             raise ConfigurationUpdateFailed()
[Traceback]                         core.ProjectAliceExceptions.ConfigurationUpdateFailed: None
[Traceback]                         During handling of the above exception, another exception occurred:
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
[Traceback]                             (self._dns_host, self.port), self.timeout, **extra_kw
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
[Traceback]                             for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
[Traceback]                           File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
[Traceback]                             for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[Traceback]                         socket.gaierror: [Errno -3] Temporary failure in name resolution
[Traceback]                         During handling of the above exception, another exception occurred:
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
[Traceback]                             chunked=chunked,
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
[Traceback]                             self._validate_conn(conn)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
[Traceback]                             conn.connect()
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
[Traceback]                             conn = self._new_conn()
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
[Traceback]                             self, "Failed to establish a new connection: %s" % e
[Traceback]                         urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x62d8f5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
[Traceback]                         During handling of the above exception, another exception occurred:
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
[Traceback]                             timeout=timeout
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
[Traceback]                             method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
[Traceback]                             raise MaxRetryError(_pool, url, error or ResponseError(cause))
[Traceback]                         urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/project-alice-assistant/ProjectAlice/issues (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x62d8f5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[Traceback]                         During handling of the above exception, another exception occurred:
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 292, in onStop
[Traceback]                             bugReportManager.onStop()
[Traceback]                           File "/home/pi/ProjectAlice/core/util/BugReportManager.py", line 84, in onStop
[Traceback]                             request = requests.post(url=f'{constants.GITHUB_API_URL}/ProjectAlice/issues', data=json.dumps(data), auth=self.ConfigManager.githubAuth)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/api.py", line 117, in post
[Traceback]                             return request('post', url, data=data, json=json, **kwargs)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
[Traceback]                             return session.request(method=method, url=url, **kwargs)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
[Traceback]                             resp = self.send(prep, **send_kwargs)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
[Traceback]                             r = adapter.send(request, **kwargs)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
[Traceback]                             raise ConnectionError(e, request=request)
[Traceback]                         requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/project-alice-assistant/ProjectAlice/issues (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x62d8f5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[Project Alice]                     Shutdown completed, see you soon!

**Comment by Psychokiller1888** [comment]
This was implemented yesterday, if offline, no reporting :-)
