### ISSUE TITLE
widgets improvement ideas

### ISSUE THREAD

**Issue by maxbachmann** [project-alice-assistant/ProjectAlice#65]
Ideas:
- widgets can already be stacked inside each other and be aligned to another module. It might be useful to be able to move the "parent" widget and keept the positioning of the "child" widgets
- the add/remove buttons in the top right corner should not block the complete top bar from moving widgets into there

**Comment by Psychokiller1888** [comment]
Although I like the idea, for now it is only zindexing the tiles and not parenting them

**Comment by maxbachmann** [comment]
sure just some ideas I had yesterday and did not want to forget.
