### ISSUE TITLE
New notification loop 

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#652]
Hi Guys, 

i'm on 1.0.0 RC3, just checked in to give Alice some love and noticed a couple of things.

1. In my Skills tab on the web UI i only show "Telegram" as being installed despite all the usual skills like redqueen , HA etc etc being installed. None of the installed skills are listed in the store to download which makes sense :).
2. So i tried installing a skill from the store to see if it would trigger showing all my installed skills and i got the following loop

>[DialogTemplateManager]             Skill OvenTemperatureConversion is new
[DialogTemplateManager]             Building dialog templates cache
[SnipsNlu]                          Preparing NLU training file
[SnipsNlu]                          Training Snips NLU
[SnipsNlu]                          Generated dataset for training
[WebUINotificationManager]          Adding notification: NLU training
[SnipsNlu]                          Begin training...
[ThreadManager]                     Started new thread NLUTraining, thread count: 21
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training
[WebUINotificationManager]          Adding notification: NLU training

**Comment by philipp2310** [comment]
Should not be an endless loop, but just a notification that plops up while the training is running. When the training is over it will update one last time with "Training completed".

Regarding the skills not showing everything - damn.. thought it was caused by a manually created skill on my end that caused this... Don't know of a change in the skills UI, but will investigate later on

**Comment by LazzaAU** [comment]
On a side note... Today i clicked the dev tab, had a little look around in there (nice job by the way, youve been a busy lad :) ) then  i went back to skills tab and all my skills showed up. Not sure  if that helps with the missing skills as mentioned above but thought it was worth mentioning

**Comment by philipp2310** [comment]
I would guess your backend updated, but the frontend was still using the buffered skill data. After visiting the devMode, all skills are reloaded, now with the new backend information including the intents and utterances :)

but devmode is another good hint - I have to check if the intent editing got broken by the changes for the skills :)
