### ISSUE TITLE
[BUG]: RedQueen's Random Chatter rudeness

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#669]
### What part of the skill does it concern?

Voice interaction

### Description of the bug

I have set the RedQueens timing for the random chatter be more frequent just for monitoring activity and wellness.  100-500

I have observed that random chatter from the RedQueen seems to also be triggered (co-incidence?) following the wakeword being detected which will be then captured as a user request. This of course is then followed by a "not understood" loop and eventually Alice gives up and confused.  Usually she will recover after a period of time but has occasionally needed a restart to recover.

### Steps To Reproduce

Go to skills, select a shorter time span for random chatter
reload the changes
say wakeword as a normal session start
note if she gives a random comment
may take several tries, happens more if a longer rest between requests

### Additional Information

Related but separate is often the random chatter will immediately follow a response to a request.  Is confusing to hear a joke followed by a comment of being tired  :)

If the timer could be reset upon wakeword detect it should resolve both chatter issues.

**Comment by philipp2310** [comment]
Issue solved in RedQueen skill:
- onWakeword clear the timer and create a new one after x minutes

Dialog flows taking more time than time between chatter might still interrupt but should never happen!
