### ISSUE TITLE
[BUG]: Switching tts when using local pico?

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#673]
### Description of the bug

[Thread-2800208] - [INFO] - [TTSManager]                        Connected to
 internet, switching TTS

If using the local pico for tts Alice goes through this cycle interrupting her service for an unneeded change of nothing.

### Steps To Reproduce

Disable internet service then re-enable 

### Additional Information

A switch of tts should only be needed IF using an online service for either asr or tts is being used.

**Comment by philipp2310** [comment]
When using an offline TTS, losing internet is not the problem - regaining is, as it is trying to switch to an online tts, even though there is none selected.

**Comment by philipp2310** [comment]
while the reloading is unnecessary - apart from the log message this has no impact. The reload is especially for pico not even taking one second, as nothing is done on start of picoTTS.

Was there a reason for this bug report apart from the log message?
