### ISSUE TITLE
[BUG]: If there is no change in node red, new scenario? 

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#674]
### Description of the bug

[MainThread] - [INFO] - [NodeRedManager]                    New scenario node found for skill AliceCore: alicecore

Seems harmless but is this just checking for a change?

### Steps To Reproduce

Is displayed in Syslog on every start / restart

**Comment by philipp2310** [comment]
can you please verify if the following file exists for you:
`~/.node-red/node_modules/alicecore/package.json`

it missing could be caused by missing permissions for alice to write there, maybe a manual NR or Alice installation. Or a failed NR installation per se

**Comment by mjlill** [comment]
The sym link was incomplete.  Remade sym link and all looks good :)
May have been an install bump. I would not have thought to look in the ~/.node-red folder
Thank you
