### ISSUE TITLE
[BUG]:Alice doesn't stop listening after a capture 

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#675]
### Description of the bug

[Voice activity]
Down on device AliceCore
[17:07:39]
[Dialogue]
Was asked to end session with id "30aea696-5a77-49de-a82a-6fce74fff356" by saying "If you yelled for 8 years, 7 months and 6 days, you will have produced enough sound energy to heat one cup of coffee."
[17:07:39]
[Asr]
Capturing text: ""
[17:07:39]
[Asr]
Capturing text: ""
[17:07:39]
[Asr]
Capturing text: ""
[17:07:39]
[Asr]
Capturing text: ""
[17:07:39]
[Asr]
Capturing text: ""
[17:07:40]
[Asr]
Was asked to start listening on device AliceCore

### Steps To Reproduce

Unknown; Just observation in AliceWatch

### Additional Information

With the continuing capture she gets a headache trying to process the next captured audio that is from hearing herself talk. 
It appears that capturing is not turned off until after each session is completed.
Eventually she stops listening and then often does not even hear the wakeword although the up/down continues.

**Comment by philipp2310** [comment]
Why is it starting to listen after capturing lots of empty text? Was there a new Hotword detected or something else cut out?
We see a VAD down, but no VAD up afterwards - is she really listening or is it just showing that log?

You say she hears herself, but the capture is empty?
