### ISSUE TITLE
[BUG]: Audio input flow seems wrong at times

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#676]
### Description of the bug

Following an AliceWatch flow, I see this (filtered):
[Hotword]  Detected on device
[Hotword]  Was asked to toggle itself off 
[Dialogue] Session with id .... was started ....
Tts]       Was asked to say "yeah?"
[Voice activity]  Up on device
[Asr]      Was asked to start listening 
[Voice activity]  Down on device 
[Asr]      Capturing text: ""
[Asr]      Capturing text: "where was i"
[Asr]      Capturing text: "got decoded words here"
[Asr]      Was asked to stop listening 
[Nlu]      Was asked to parse input "decoded words"
[Nlu]      Intent detected 

At this point she should not hear anything additional until
 "Not Understand", 
 Session ended with "as expected" or "a timeout"

[Voice activity]   Down on device 

There was no input so how is a new intent detected? And she fails without finishing the original Intent Detected.. 
[Dialogue] New intent detected 
[Nlu]      Intent not recognized for ""
[Dialogue] Was asked to continue session .. by saying "I'm sorry but
[Tts]      Was asked to say "I'm sorry but ....

Sometimes will fall through gracefully.
[Dialogue] Was asked to end session with .....  by saying "Oh Hello"
[Tts]      Was asked to say "Oh Hello"
[Dialogue] Session with .... was ended on device....The session ended as expected.

### Steps To Reproduce

Observe the AliceWatch flow process

### Additional Information

That action is the same on a Pi4 and on a Pi3B+
It also seems to leave the wakeword disabled until a restart is executed

**Comment by philipp2310** [comment]
Please don't cut out logging unless it has sensitive information.
Explain your issue and post the whole log - don't mix log output and explanation unless you know the reason for the issue.

I have no idea what you are trying to show with this report

**Comment by mjlill** [comment]
Sorry, filtered it for clarity to be helpful.
