### ISSUE TITLE
[BUG]: HLC does not install properly

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#677]
### Description of the bug

HLC has an  error in the path to the configuration.yml

 mv ~/.config/HermesLedControl   ~/.config/hermesLedControl

### Steps To Reproduce

Installation of ProjectAlice manually. Not tested with the Cli
$ ps ax|grep py   will show HLC not running

### Additional Information

After renaming the path, it was confirmed HLC was started & running

**Comment by philipp2310** [comment]
Manual Installations are not supported. Anything can go wrong, there is no way for us to find out what went wrong for you. sorry.
