### ISSUE TITLE
[BUG]: Audio input & output not available in Admin settings

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#678]
### Description of the bug

After fresh install on the current RPiOS and rc3 + master, the option to select an audio device is blank and nothing shows for the pull down.

### Steps To Reproduce

Do an install see if same results

**Comment by philipp2310** [comment]
Probably only in the newest raspi image?

**Comment by mjlill** [comment]
Possibly do to new 0906 Legacy RPiOS? Maybe..   
config.json was as default and audio works.
Is the only issue that I have notice with Alice at this point :)

**Comment by mjlill** [comment]
After fresh re-install of Alice the admin audio issue has vanished. May have just been a bump.  All appears good in early inspection! :)
