### ISSUE TITLE
[BUG]: skill creation error

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#680]
### Description of the bug

Just trying to create a skill from Dev mode and i get the below error 

>[SkillManager]                      Creating new skill "SendTxtMessage"
[SkillManager]                      Created SendTxtMessage skill
[SkillManager]                      Cannot load skill install file for skill SendTxtMessage, skipping: [Errno 2] No such file or directory: '/home/pi/ProjectAlice/skills/SendTxtMessage/SendTxtMessage.install'
[SkillManager]                      Skill "SendTxtMessage" does not exist in skills manager

That's after adding the skillname, category etc and clicking "create"

### Steps To Reproduce

1. go to dev mode
2. click "create skill"
3. fill in the details
4. click "create"

### Additional Information

Have tried 4 times now and have rebooted and re tried. Same result .i'm on 'master' and it worked a few weeks ago so not sure what changed but doesnt make the directories or anything

**Comment by philipp2310** [comment]
Nothing changed for the creation since month - only in editing after initial creation where some changes.
But strangely it is reproducible for me.. will let you know when I figure out what changed (first thought, some permission issue?)

**Comment by philipp2310** [comment]
fixed - no restart of Alice required, skill kit will pull a new version as soon as you hit create. (in rare cases pip upgrade only works on the second try)
