### ISSUE TITLE
[BUG]:Alice does not capture voice very well. 

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#681]
### Description of the bug

Did a fresh install with the new RPiOS on Sept 8 and she worked well, giving prompt responses to a voice request.  A day or two later till currently, she does not capture voice or very limited of one or two words.  There are no errors I could find in the logs and nothing shows in the syslog. I have reinstalled several times, using manual and the cli, with AIY usb webcam & RS2 hats with same sad results. 

### Steps To Reproduce

Either a fresh install or maybe just an upgrade so have current RC3-master
Use normal voice requests
observe AliceWatch for success

### Additional Information

Alice appears to be fully functional and responsive in all other services, dialogview, random chatter, (general usage)

**Comment by philipp2310** [comment]
You said in discord the same is happening in your old B4 version as well?

**Comment by mjlill** [comment]
No, my B4 is still okay as it didn't do any updates (probably too old) sry if any confusion there. Is only the RC3 - master. It was fine while we were testing the the language switching but I think (memory nay be off) it was the next day the voice capture was not good. Wakeword is very responsive.

**Comment by philipp2310** [comment]
Everything is fine for me in master, with RS2 and coqui(DE). So it is not a general problem. Please try changing your ASR, as this seems to be the failing part. Maybe your downloaded coqui model broke (or there is an issue with english coqui at the moment?) As you were quite happy with SnipsASR before, could you try that or VOSK maybe?

**Comment by mjlill** [comment]
Only asr that almost works is the vosk on a Pi4. The Pi3B+ has no observable change in the performance with either snips, coqui or vosk.

**Comment by philipp2310** [comment]
Sounds like you got an performance issue when there is a difference in Rpi3&4.
What is your system usage while the ASR is actively running?

**Comment by mjlill** [comment]
![Pi3B+-status](https://user-images.githubusercontent.com/52712060/190280542-d079203a-5614-4fd4-b850-e1a4185593c8.jpg)
![pi4-2-status](https://user-images.githubusercontent.com/52712060/190280553-fe988351-7f2b-4a4a-9776-2306d5ccfcb7.jpg)

**Comment by mjlill** [comment]
To turn over all the stones, I did a complete fresh install using the cli with the RS2 hat. Saw no errors. No audio although pretest was good. Had to select the seeeds for input/output and got the ding on the restart. She hears the wakeword but capture audio is same with may one or two words for the classic "what is the time"  Of course is on EN and no other changes to the settings except HLC & status to on.
Where to from here??

**Comment by philipp2310** [comment]
The error was fixed. It had nothing todo with ASR but was a RedQueen issue.
