### ISSUE TITLE
[BUG]: Error when switching to vosk asr

### ISSUE THREAD

**Issue by mjlill** [project-alice-assistant/ProjectAlice#684]
### Description of the bug

[22:18:03.731]
[VoskAsr]
Starting Vosk Asr
[22:18:03.736]
[VoskAsr]
Loading model
[22:18:04.403]
[ASRManager]
Couldn't start any ASR, going down

[22:18:04.671]
[Traceback]
requests.exceptions.SSLError: HTTPSConnectionPool(host='alphacephei.com', port=443): Max retries exceeded with url: /vosk/models/model-list.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)')))

### Steps To Reproduce

In the Admin tab, selected vosk from coqui

**Comment by mjlill** [comment]
This locks Alice into a loop. Manually need to edit the config.json to change from vosk

**Comment by Psychokiller1888** [comment]
This is on Vosk's side, their SSL certificate is expired
