### ISSUE TITLE
Interface for devs

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/ProjectAlice#73]
I was thinking about a few points:

- Adding an option to config for the interface: "enableDevConsole: False"
- This unlocks a new section on the interface, for devs
   - It hosts our own "Project Alice" console, were devs can mod their modules, a shameless clone of snips console, but local!
   - It allows one to upload a module directly into Alice, usefull
   - It allows new module direct creation
   - It allows direct PR to the module repository

What do you guys think?

**Comment by maxbachmann** [comment]
I would really like that
